import React, { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, Gavel, MessageSquare, ShieldAlert, Users, XCircle, Zap } from 'lucide-react';
import { GameState, Company, CorporateBoardMeetingAgenda, CorporateBoardroomSession } from '../../types';

interface Props { state: GameState; company: Company; onStart:(companyId:string,agenda:CorporateBoardMeetingAgenda,proposal:string)=>void; onReport:(sessionId:string,role:string,report?:string)=>void; onDebate:(sessionId:string,position:'FOR'|'AGAINST'|'NEUTRAL',argument:string)=>void; onAmend:(sessionId:string,text:string)=>void; onPressure:(sessionId:string,holderId:string,demand:string,response:'ADDRESSED'|'IGNORED'|'CONCESSION')=>void; onVote:(sessionId:string,vote:'FOR'|'AGAINST'|'ABSTAIN')=>void; onAdvance:(sessionId:string)=>void; }
const agendas:{id:CorporateBoardMeetingAgenda;label:string;description:string;defaultProposal:string}[]=[
{id:'STRATEGY',label:'Strategy',description:'Set the company direction.',defaultProposal:'Approve a three-year growth strategy focused on expanding market share.'},{id:'CAPITAL_ALLOCATION',label:'Capital',description:'Allocate cash and investment.',defaultProposal:'Approve a capital allocation plan prioritising growth investment.'},{id:'CEO_PERFORMANCE',label:'CEO Review',description:'Assess CEO performance.',defaultProposal:'Approve the CEO performance review and new strategic targets.'},{id:'EXECUTIVE_COMPENSATION',label:'Executive Pay',description:'Approve leadership compensation.',defaultProposal:'Approve a performance-linked executive compensation package.'},{id:'DIVIDEND',label:'Dividend',description:'Return cash to shareholders.',defaultProposal:'Approve an increased shareholder dividend distribution.'},{id:'DEBT',label:'Debt',description:'Authorise financing.',defaultProposal:'Authorise additional debt financing to strengthen expansion capacity.'},{id:'CAPEX',label:'CAPEX',description:'Expand assets and capacity.',defaultProposal:'Approve a major capital expenditure programme to expand capacity.'},{id:'M_AND_A',label:'M&A',description:'Authorise acquisition activity.',defaultProposal:'Approve an acquisition mandate targeting a strategic competitor.'},{id:'RESTRUCTURE',label:'Restructure',description:'Change the organisation and costs.',defaultProposal:'Approve a workforce and operating-cost restructuring programme.'},{id:'RISK_CRISIS',label:'Risk / Crisis',description:'Respond to an emerging threat.',defaultProposal:'Approve an emergency risk-response plan to stabilise the company.'}];
const phaseOrder=['AGENDA','EXECUTIVE_REPORTS','DIRECTOR_DEBATE','AMENDMENTS','SHAREHOLDER_PRESSURE','FINAL_VOTE','CLOSED'];
const phaseLabel=(p:string)=>p.replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase());
export const CorporateBoardMeetingView:React.FC<Props>=({state,company,onStart,onReport,onDebate,onAmend,onPressure,onVote,onAdvance})=>{
 const [agenda,setAgenda]=useState<CorporateBoardMeetingAgenda>('STRATEGY'); const [proposal,setProposal]=useState(agendas[0].defaultProposal); const [vote,setVote]=useState<'FOR'|'AGAINST'|'ABSTAIN'>('FOR'); const [argument,setArgument]=useState(''); const [amendment,setAmendment]=useState(''); const [pressureResponse,setPressureResponse]=useState<'ADDRESSED'|'IGNORED'|'CONCESSION'>('ADDRESSED');
 const meetings=state.corporateSystem?.boardMeetings?.filter(m=>m.companyId===company.id)||[]; const active=meetings.find(m=>m.outcome==='IN_PROGRESS'); const session=active?.sessionId?state.corporateSystem?.boardroomSessions?.find(s=>s.id===active.sessionId):undefined; const board=state.corporateSystem?.boardSeats?.[company.id]||[]; const shareholders=state.corporateSystem?.shareholderRecords?.[company.id]||[]; const playerCan=['OWNER','CHAIRPERSON','DIRECTOR'].includes((company.playerOwnershipPercentage>=51?'OWNER':board.some(b=>b.isPlayerSeat)?'DIRECTOR':'NONE'));
 const support=useMemo(()=>board.length?board.reduce((a,b)=>a+b.supportLevel*b.representedOwnershipPercent,0)/Math.max(1,board.reduce((a,b)=>a+b.representedOwnershipPercent,0)):0,[board]);
 const select=(id:CorporateBoardMeetingAgenda)=>{setAgenda(id);setProposal(agendas.find(a=>a.id===id)?.defaultProposal||'');};
 const currentPhase=session?.phase||'AGENDA'; const phaseIndex=phaseOrder.indexOf(currentPhase);
 return <div className="space-y-4">
  {!session && <div className="bg-zinc-950/70 border border-zinc-800 rounded-2xl p-4"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-amber-400 text-[10px] font-black uppercase tracking-widest"><Gavel className="w-4 h-4"/> Boardroom 2.0</div><h4 className="text-lg font-black text-zinc-100 mt-1">Convene a Living Board Meeting</h4><p className="text-[11px] text-zinc-500">Board confidence: <b className="text-amber-300">{support.toFixed(0)}%</b>. Meetings now progress through reports, debate, amendments, shareholder pressure and a final vote.</p></div><ShieldAlert className="w-7 h-7 text-zinc-700"/></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-2 mt-4">{agendas.map(a=><button key={a.id} onClick={()=>select(a.id)} className={`text-left p-2.5 rounded-xl border text-[10px] font-bold ${agenda===a.id?'bg-amber-400 text-zinc-950 border-amber-300':'bg-zinc-900 text-zinc-300 border-zinc-800 hover:border-zinc-600'}`}><div>{a.label}</div><div className="mt-1 text-[9px] font-normal opacity-70">{a.description}</div></button>)}</div><textarea value={proposal} onChange={e=>setProposal(e.target.value)} className="mt-3 w-full min-h-20 bg-zinc-900 border border-zinc-800 rounded-xl p-3 text-xs text-zinc-200 outline-none focus:border-amber-400"/><button disabled={!playerCan||!proposal.trim()} onClick={()=>onStart(company.id,agenda,proposal)} className="mt-2 w-full sm:w-auto px-4 py-2.5 rounded-xl bg-amber-400 text-zinc-950 text-[10px] font-black disabled:opacity-40">Open Boardroom</button></div>}
  {session && active && <>
   <div className="bg-zinc-950/70 border border-amber-500/30 rounded-2xl p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-amber-400">Live Corporate Institution</div><h4 className="text-lg font-black text-zinc-100">{active.title}</h4><p className="text-[11px] text-zinc-400 mt-1">{active.proposal}</p></div><Zap className="w-6 h-6 text-amber-400"/></div><div className="grid grid-cols-3 sm:grid-cols-7 gap-1.5 mt-4">{phaseOrder.map((p,i)=><div key={p} className={`p-2 rounded-lg text-[8px] font-black text-center ${i<phaseIndex?'bg-emerald-500/15 text-emerald-300':i===phaseIndex?'bg-amber-400 text-zinc-950':'bg-zinc-900 text-zinc-600'}`}>{i+1}. {phaseLabel(p)}</div>)}</div></div>
   {currentPhase!=='FINAL_VOTE' && currentPhase!=='CLOSED' && <div className="flex justify-end"><button onClick={()=>onAdvance(session.id)} className="px-4 py-2 rounded-xl bg-zinc-100 text-zinc-950 text-[10px] font-black">Advance Boardroom Stage <ChevronRight className="w-3 h-3 inline ml-1"/></button></div>}
   {currentPhase==='AGENDA' || currentPhase==='EXECUTIVE_REPORTS' ? <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><ActionCard icon={<MessageSquare/>} title="CEO Presentation" body="Let the CEO make the strategic case before directors debate." button="Hear CEO" onClick={()=>onReport(session.id,'CEO')}/><ActionCard icon={<MessageSquare/>} title="CFO Presentation" body="Put cash, debt, profitability and financial risk on the record." button="Hear CFO" onClick={()=>onReport(session.id,'CFO')}/></div>:null}
   {(currentPhase==='DIRECTOR_DEBATE'||currentPhase==='EXECUTIVE_REPORTS') && <div className="bg-zinc-950/60 border border-zinc-800 rounded-2xl p-4"><h5 className="text-xs font-black text-zinc-200">Director Debate</h5><div className="flex gap-2 mt-3"><button onClick={()=>onDebate(session.id,'FOR',argument||'I support the proposal because its strategic benefits outweigh the identified risks.')} className="px-3 py-2 rounded-lg bg-emerald-400 text-zinc-950 text-[10px] font-black">Argue FOR</button><button onClick={()=>onDebate(session.id,'AGAINST',argument||'I oppose the proposal because the board should protect the company from excessive risk.')} className="px-3 py-2 rounded-lg bg-rose-400 text-zinc-950 text-[10px] font-black">Argue AGAINST</button><button onClick={()=>onDebate(session.id,'NEUTRAL',argument||'I need further evidence before supporting this proposal.')} className="px-3 py-2 rounded-lg bg-zinc-800 text-zinc-200 text-[10px] font-black">Stay NEUTRAL</button></div><textarea value={argument} onChange={e=>setArgument(e.target.value)} placeholder="Your boardroom argument..." className="mt-3 w-full min-h-16 bg-zinc-900 border border-zinc-800 rounded-xl p-3 text-xs text-zinc-200"/>{session.debates.length>0&&<div className="mt-3 space-y-2">{session.debates.slice(-4).map(d=><div key={d.id} className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800"><b className="text-[10px] text-zinc-200">{d.speakerName}</b><span className="text-[9px] text-amber-300 ml-2">{d.position}</span><div className="text-[10px] text-zinc-400 mt-1">{d.argument}</div></div>)}</div>}</div>}
   {(currentPhase==='AMENDMENTS'||currentPhase==='DIRECTOR_DEBATE') && <div className="bg-zinc-950/60 border border-zinc-800 rounded-2xl p-4"><h5 className="text-xs font-black text-zinc-200">Amend the Resolution</h5><p className="text-[10px] text-zinc-500 mt-1">Directors can alter the proposal before the final vote. Amendments are themselves voted on.</p><textarea value={amendment} onChange={e=>setAmendment(e.target.value)} placeholder="Example: cap new debt at 10% of enterprise value..." className="mt-3 w-full min-h-16 bg-zinc-900 border border-zinc-800 rounded-xl p-3 text-xs text-zinc-200"/><button disabled={!amendment.trim()} onClick={()=>{onAmend(session.id,amendment);setAmendment('')}} className="mt-2 px-3 py-2 rounded-lg bg-zinc-100 text-zinc-950 text-[10px] font-black disabled:opacity-40">Submit Amendment</button>{session.amendments.length>0&&<div className="mt-3 space-y-2">{session.amendments.slice(-3).map(a=><div key={a.id} className="text-[10px] p-2.5 rounded-xl bg-zinc-900 border border-zinc-800"><b className={a.accepted?'text-emerald-300':'text-rose-300'}>{a.accepted?'ACCEPTED':'REJECTED'}</b> <span className="text-zinc-400">{a.text}</span></div>)}</div>}</div>}
   {(currentPhase==='SHAREHOLDER_PRESSURE'||currentPhase==='AMENDMENTS') && <div className="bg-zinc-950/60 border border-zinc-800 rounded-2xl p-4"><h5 className="text-xs font-black text-zinc-200">Shareholder Pressure</h5><div className="space-y-2 mt-3">{shareholders.filter(h=>h.holderType!=='PLAYER').slice(0,5).map(h=><div key={h.holderId} className="flex flex-wrap items-center gap-2 p-2.5 rounded-xl bg-zinc-900 border border-zinc-800"><div className="flex-1"><b className="text-[10px] text-zinc-200">{h.holderName}</b><div className="text-[9px] text-zinc-500">{h.ownershipPercent.toFixed(1)}% · {h.holderType}</div></div><select value={pressureResponse} onChange={e=>setPressureResponse(e.target.value as any)} className="bg-zinc-950 border border-zinc-700 rounded-lg text-[9px] p-1.5"><option value="ADDRESSED">Address</option><option value="CONCESSION">Concede</option><option value="IGNORED">Ignore</option></select><button onClick={()=>onPressure(session.id,h.holderId,'Protect shareholder value and provide a credible explanation for the board proposal.',pressureResponse)} className="px-2.5 py-1.5 rounded-lg bg-amber-400 text-zinc-950 text-[9px] font-black">Respond</button></div>)}</div></div>}
   {currentPhase==='FINAL_VOTE' && <div className="bg-zinc-950/60 border border-zinc-800 rounded-2xl p-4"><h5 className="text-xs font-black text-zinc-200">Chair Calls Final Vote</h5><p className="text-[10px] text-zinc-500 mt-1">Your vote will be combined with the AI directors using represented voting weight.</p><div className="flex gap-2 mt-3">{(['FOR','AGAINST','ABSTAIN'] as const).map(v=><button key={v} onClick={()=>setVote(v)} className={`px-3 py-2 rounded-lg text-[10px] font-black ${vote===v?(v==='FOR'?'bg-emerald-400 text-zinc-950':v==='AGAINST'?'bg-rose-400 text-zinc-950':'bg-zinc-200 text-zinc-950'):'bg-zinc-900 text-zinc-400 border border-zinc-800'}`}>{v}</button>)}<button onClick={()=>onVote(session.id,vote)} className="ml-auto px-4 py-2 rounded-lg bg-amber-400 text-zinc-950 text-[10px] font-black">Call Vote</button></div></div>}
   <div className="grid grid-cols-1 lg:grid-cols-2 gap-3"><div className="bg-zinc-950/50 border border-zinc-800 rounded-2xl p-4"><div className="flex items-center gap-2 text-xs font-black text-zinc-200"><Users className="w-4 h-4 text-amber-400"/> Directors</div><div className="space-y-2 mt-3">{board.map(b=><div key={b.id} className="flex items-center justify-between p-2.5 rounded-xl bg-zinc-900 border border-zinc-800"><div><div className="text-[10px] font-bold text-zinc-200">{b.holderName}{b.isPlayerSeat?' · You':''}</div><div className="text-[8px] text-zinc-500">{b.agenda.replaceAll('_',' ')} · support {b.supportLevel.toFixed(0)}</div></div><span className="text-[9px] font-black text-amber-300">{b.representedOwnershipPercent.toFixed(1)}%</span></div>)}</div></div><div className="bg-zinc-950/50 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black text-zinc-200">Boardroom Narrative</div><div className="space-y-2 mt-3">{session.narrative.slice(-7).reverse().map((n,i)=><div key={i} className="text-[9px] text-zinc-400 p-2 rounded-lg bg-zinc-900">{n}</div>)}</div></div></div>
  </>}
  <div className="bg-zinc-950/50 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black text-zinc-200">Recent Corporate Governance</div><div className="space-y-2 mt-3">{meetings.filter(m=>m.outcome!=='IN_PROGRESS').slice(-5).reverse().map(m=><div key={m.id} className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800"><div className="flex justify-between"><span className="text-[10px] font-black text-zinc-200">{m.title}</span>{m.outcome==='APPROVED'?<CheckCircle2 className="w-3.5 h-3.5 text-emerald-400"/>:<XCircle className="w-3.5 h-3.5 text-rose-400"/>}</div><div className="text-[9px] text-zinc-500 mt-1">{m.outcome} · {m.quorumPercent.toFixed(0)}% quorum</div>{m.crisisFlags?.length?<div className="text-[9px] text-rose-300 mt-1 flex gap-1"><AlertTriangle className="w-3 h-3"/>{m.crisisFlags.map(x=>x.replace(/_/g,' ')).join(' · ')}</div>:null}<div className="text-[9px] text-zinc-400 mt-1">{m.outcomeReason}</div></div>)}{meetings.filter(m=>m.outcome!=='IN_PROGRESS').length===0&&<div className="text-[10px] text-zinc-500">No concluded boardroom sessions yet.</div>}</div></div>
 </div>
};
const ActionCard=({icon,title,body,button,onClick}:{icon:React.ReactNode;title:string;body:string;button:string;onClick:()=>void})=><div className="bg-zinc-950/60 border border-zinc-800 rounded-2xl p-4"><div className="text-amber-400 w-5 h-5">{icon}</div><h5 className="text-xs font-black text-zinc-200 mt-2">{title}</h5><p className="text-[10px] text-zinc-500 mt-1">{body}</p><button onClick={onClick} className="mt-3 px-3 py-2 rounded-lg bg-zinc-100 text-zinc-950 text-[10px] font-black flex items-center gap-1">{button}<ChevronRight className="w-3 h-3"/></button></div>;
