import React,{useState} from 'react';
import {GameState} from '../../types';
import {ensureBankingSystemProfile} from '../../engine/bankingEngine';
import {ensureLivingBankingProfile,openLivingBankAccount,LivingAccountProduct} from '../../engine/livingBankingEngine';
import {ensurePoliticalGovernance,runForPublicOffice,managePublicOffice,PublicManagementArea} from '../../engine/politicalGovernanceEngine';

export const LivingBankingPanel:React.FC<{state:GameState;onStateChange?:()=>void}>=({state,onStateChange})=>{
 const banking=ensureBankingSystemProfile(state), living=ensureLivingBankingProfile(state); const [bank,setBank]=useState(banking.institutions[0]?.id||''); const [product,setProduct]=useState<LivingAccountProduct>('SAVINGS'); const [amount,setAmount]=useState(5000); const [msg,setMsg]=useState('');
 const open=()=>{const r=openLivingBankAccount(state,bank,product,amount);setMsg(r.message);onStateChange?.()};
 return <div className="space-y-4"><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black uppercase tracking-widest text-amber-400">Living Banking</div><div className="grid md:grid-cols-4 gap-2 mt-3"><select value={bank} onChange={e=>setBank(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs">{banking.institutions.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={product} onChange={e=>setProduct(e.target.value as LivingAccountProduct)} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs">{['CHECKING','SAVINGS','HIGH_YIELD','MONEY_MARKET','CD','RETIREMENT','OFFSHORE','BUSINESS'].map(x=><option key={x}>{x}</option>)}</select><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs"/><button onClick={open} className="bg-amber-500 text-zinc-950 rounded-xl font-black text-xs">Open account</button></div>{msg&&<div className="mt-3 text-xs text-emerald-300">{msg}</div>}</div><div className="grid md:grid-cols-2 gap-3"><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black text-zinc-200">Your accounts</div>{banking.depositAccounts.map(a=><div key={a.id} className="mt-2 p-3 bg-zinc-950 rounded-xl text-xs flex justify-between"><span>{a.bankName} · {a.accountType||a.type}</span><span className="text-emerald-300">${a.balance.toLocaleString()} · {a.interestRateAnnual}%</span></div>)}</div><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black text-zinc-200">Banking events</div>{living.monthlyEvents.slice(0,6).map((e,i)=><div key={i} className="mt-2 text-xs text-zinc-400"><b className="text-zinc-200">{e.title}</b><div>{e.narrative}</div></div>)}</div></div></div>
};

export const PoliticalGovernancePanel:React.FC<{state:GameState;onStateChange?:()=>void}>=({state,onStateChange})=>{
 const p=ensurePoliticalGovernance(state), o=state.politics.currentOffice; const [office,setOffice]=useState('Mayor'); const [jur,setJur]=useState(state.character.residenceCity); const [budget,setBudget]=useState(25000); const [area,setArea]=useState<PublicManagementArea>('INFRASTRUCTURE'); const [delta,setDelta]=useState(5); const [msg,setMsg]=useState('');
 const launch=()=>{const r=runForPublicOffice(state,office,jur,budget);setMsg(r.message);onStateChange?.()}; const act=()=>{const r=managePublicOffice(state,area,delta,`Public ${area.toLowerCase()} program`);setMsg(r.message);onStateChange?.()};
 return <div className="space-y-4"><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black uppercase tracking-widest text-cyan-400">Political Career & Public Administration</div><div className="text-sm font-black mt-1">{o.title} · {o.cityOrNation}</div><div className="grid md:grid-cols-4 gap-2 mt-3"><select value={office} onChange={e=>setOffice(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs">{['City Councillor','Mayor','Member of Parliament / Senator','Cabinet Minister','President / Prime Minister'].map(x=><option key={x}>{x}</option>)}</select><input value={jur} onChange={e=>setJur(e.target.value)} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs"/><input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs"/><button onClick={launch} className="bg-cyan-400 text-zinc-950 rounded-xl font-black text-xs">Launch campaign</button></div><div className="grid md:grid-cols-4 gap-2 mt-3"><select value={area} onChange={e=>setArea(e.target.value as PublicManagementArea)} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs">{['BUDGET','INFRASTRUCTURE','HEALTH','EDUCATION','PUBLIC_SAFETY','ECONOMY','ENVIRONMENT','HOUSING','TRANSPORT','FOREIGN_AFFAIRS'].map(x=><option key={x}>{x}</option>)}</select><input type="number" value={delta} onChange={e=>setDelta(Number(e.target.value))} className="bg-zinc-950 border border-zinc-700 rounded-xl p-2 text-xs"/><button onClick={act} className="bg-emerald-500 text-zinc-950 rounded-xl font-black text-xs">Execute policy</button><div className="text-xs text-zinc-400 p-2">Approval: {o.approvalRating}% · Capital: {o.politicalCapital}</div></div>{msg&&<div className="mt-3 text-xs text-emerald-300">{msg}</div>}</div><div className="grid md:grid-cols-2 gap-3"><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black">Active & recent campaigns</div>{p.campaigns.slice(-8).reverse().map(c=><div key={c.id} className="mt-2 p-3 bg-zinc-950 rounded-xl text-xs flex justify-between"><span>{c.office} · {c.jurisdiction}</span><span>{c.status} · {c.polling.toFixed(1)}%</span></div>)}</div><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><div className="text-xs font-black">Public administration history</div>{p.policyHistory.slice(0,8).map((x,i)=><div key={i} className="mt-2 text-xs text-zinc-400"><b className="text-zinc-200">{x.area}</b> — {x.effect}</div>)}</div></div></div>
};
