import React,{useState} from 'react';
import {GameState,RealEstateDevelopmentType} from '../../types';
import {Building2,Landmark,HardHat,ShoppingBag,TrendingUp,PlusCircle,CheckCircle2,Users,FileText,Shield,Scale} from 'lucide-react';
import {ensureRealEstatePlatform,buyRealEstateListing,buyLandParcel,startRealEstateDevelopment} from '../../engine/realEstatePlatformEngine';
import {ensureRealEstateIndustry,seedRealEstateIndustry,createCommercialLease,createPermit,scheduleInspection,createConstructionContract,createJV,createSPV,createDevelopmentFinance,createPreSale,startAuction} from '../../engine/realEstateIndustryEngine';

export const RealEstatePlatformView:React.FC<{state:GameState;onStateChange?:()=>void}>=({state,onStateChange})=>{
 const p=ensureRealEstatePlatform(state); const r=seedRealEstateIndustry(state);
 const [tab,setTab]=useState<'market'|'land'|'projects'|'industry'|'institutional'>('market'); const [toast,setToast]=useState('');
 const [landName,setLandName]=useState('Prime Development Site'); const [landPrice,setLandPrice]=useState(2500000); const [landArea,setLandArea]=useState(5000); const [zoning,setZoning]=useState('Mixed Use');
 const [projectLand,setProjectLand]=useState(''); const [projectName,setProjectName]=useState('Harbour Master Planned District'); const [projectType,setProjectType]=useState<RealEstateDevelopmentType>('Master Planned Community'); const [budget,setBudget]=useState(30000000);
 const act=(m:string)=>{setToast(m);onStateChange?.();setTimeout(()=>setToast(''),4500)};
 const buy=(id:string)=>act(buyRealEstateListing(state,id).message);
 const addLand=()=>{const x=buyLandParcel(state,landName,state.character.residenceCity||'Cape Town',state.character.residenceCountry||'South Africa',landArea,zoning,landPrice);act(x.message);if(x.parcel)setProjectLand(x.parcel.id)};
 const launch=()=>{const x=startRealEstateDevelopment(state,projectLand,projectName,projectType,budget,30);if(x.project){createSPV(state,x.project.id,`${projectName} SPV`);createDevelopmentFinance(state,x.project.id,'Dominium Development Bank',x.project.financingDebt,7.25);createPermit(state,x.project.id,'Planning & Development','Municipal Planning Authority');scheduleInspection(state,x.project.id,'Foundation / structural compliance');createConstructionContract(state,x.project.id,r.contractors[0]?.id||'builder_0',budget*.62);createJV(state,x.project.id,'Strategic Property Partner',budget*.15,15);createPreSale(state,x.project.id,'Anchor Buyer',x.project.expectedValue*.12);}act(x.message)};
 const industryAction=(m:string)=>act(m);
 return <div className="space-y-4">
  {toast&&<div className="p-3 rounded-xl border border-emerald-700 bg-emerald-950/60 text-emerald-200 text-xs font-bold flex gap-2"><CheckCircle2 className="w-4 h-4"/>{toast}</div>}
  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5"><Metric label="Land Bank" value={`$${p.totalLandValue.toLocaleString()}`} icon={<Landmark/>}/><Metric label="Development Pipeline" value={`$${p.totalProjectValue.toLocaleString()}`} icon={<HardHat/>}/><Metric label="Market Cycle" value={p.marketCycle} icon={<TrendingUp/>}/><Metric label="Industry Network" value={`${r.agents.length+r.contractors.length+r.professionals.length} institutions`} icon={<Users/>}/></div>
  <div className="flex gap-2 border-b border-zinc-800 pb-2 flex-wrap">{[['market','Property Market'],['land','Land Bank'],['projects','Development Projects'],['industry','Industry Network'],['institutional','Institutional']].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`px-3 py-2 rounded-xl text-xs font-black ${tab===k?'bg-amber-500/20 text-amber-300 border border-amber-500/30':'text-zinc-400 hover:bg-zinc-800'}`}>{l}</button>)}</div>
  {tab==='market'&&<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{p.listings.filter(x=>x.status==='LISTED').map(l=><Card key={l.id}><div className="flex justify-between"><div><div className="text-sm font-black text-zinc-100">{l.name}</div><div className="text-xs text-zinc-500">{l.assetType} · {l.city}</div></div><ShoppingBag className="w-5 h-5 text-amber-400"/></div><div className="grid grid-cols-2 gap-2 text-xs mt-3"><Stat label="Ask" value={`$${l.askingPrice.toLocaleString()}`}/><Stat label="Yield" value={`${l.rentalYield}%`}/><Stat label="Size" value={`${l.areaSqm.toLocaleString()} sqm`}/><Stat label="Development" value={`${l.developmentPotential}/100`}/></div><button onClick={()=>buy(l.id)} className="w-full mt-3 py-2 bg-amber-500 text-zinc-950 rounded-xl text-xs font-black">Acquire Asset</button></Card>)}</div>}
  {tab==='land'&&<div className="grid lg:grid-cols-2 gap-3"><Card><h3 className="font-black text-zinc-100">Acquire Land</h3><p className="text-xs text-zinc-500 mt-1">Hold, finance, develop, lease or sell land as a strategic asset.</p><Input label="Parcel name" value={landName} onChange={setLandName}/><Input label="Area (sqm)" value={landArea} onChange={v=>setLandArea(Number(v))} type="number"/><Input label="Purchase price" value={landPrice} onChange={v=>setLandPrice(Number(v))} type="number"/><Select value={zoning} onChange={setZoning} options={['Mixed Use','Residential','Commercial','Industrial','Hospitality','Institutional']}/><button onClick={addLand} className="w-full py-2 bg-blue-600 text-white rounded-xl text-xs font-black"><PlusCircle className="inline w-4 h-4 mr-1"/>Acquire Land</button></Card><div className="space-y-2">{p.landParcels.map(l=><Card key={l.id}><div className="flex justify-between"><div><div className="font-black text-zinc-100 text-sm">{l.name}</div><div className="text-xs text-zinc-500">{l.city} · {l.zoning} · {l.areaSqm.toLocaleString()} sqm</div></div><span className="text-xs text-emerald-400 font-black">${l.currentValue.toLocaleString()}</span></div></Card>)}</div></div>}
  {tab==='projects'&&<div className="space-y-3"><Card><h3 className="font-black">Integrated Development Pipeline</h3><div className="grid md:grid-cols-2 gap-3 mt-3"><Select value={projectLand} onChange={setProjectLand} options={['',...p.landParcels.filter(l=>l.status==='OWNED').map(l=>l.id)]} labels={['Select owned land',...p.landParcels.filter(l=>l.status==='OWNED').map(l=>l.name)]}/><Input label="Project name" value={projectName} onChange={setProjectName}/><Select value={projectType} onChange={v=>setProjectType(v as RealEstateDevelopmentType)} options={['Single Family Estate','Townhouse Development','Apartment Development','Luxury Residential Tower','Office Tower','Shopping Centre','Mixed Use District','Industrial Park','Logistics Hub','Hotel','Resort','Student Housing','Senior Living Community','Data Center','Business Park','Sports & Entertainment Complex','Healthcare Campus','Renewable Energy Site','Master Planned Community','Custom Project']}/><Input label="Total project budget" value={budget} onChange={v=>setBudget(Number(v))} type="number"/></div><button onClick={launch} className="mt-3 px-5 py-2 bg-emerald-600 text-white rounded-xl text-xs font-black">Launch Fully Structured Development</button></Card>{p.projects.map(x=><Card key={x.id}><div className="flex justify-between"><div><div className="font-black text-zinc-100">{x.name}</div><div className="text-xs text-zinc-500">{x.developmentType} · {x.city} · {x.phase}</div></div><span className="text-xs font-black text-amber-400">{x.progress}%</span></div><div className="h-2 bg-zinc-800 rounded-full mt-3 overflow-hidden"><div className="h-full bg-emerald-500" style={{width:`${x.progress}%`}}/></div><div className="grid grid-cols-3 gap-2 text-[10px] mt-3"><Stat label="Budget" value={`$${x.budget.toLocaleString()}`}/><Stat label="Expected Value" value={`$${x.expectedValue.toLocaleString()}`}/><Stat label="Jobs" value={x.jobsCreated.toLocaleString()}/></div></Card>)}</div>}
  {tab==='industry'&&<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3"><Industry title="Agents & Brokers" icon={<Users/>} items={r.agents.map(a=>`${a.name} · ${a.agency} · ${a.reputation}/100 reputation`)}/><Industry title="Property Managers" icon={<Building2/>} items={r.propertyManagers.map(a=>`${a.name} · ${a.company} · ${a.occupancyRate.toFixed(0)}% occupancy`)}/><Industry title="Contractors" icon={<HardHat/>} items={r.contractors.map(a=>`${a.name} · Quality ${a.quality}/100 · Capacity ${a.capacity}`)}/><Industry title="Architects & Engineers" icon={<FileText/>} items={r.professionals.map(a=>`${a.name} · ${a.discipline} · ${a.reputation}/100`)}/><Industry title="Tenants" icon={<Users/>} items={r.tenants.map(a=>`${a.name} · ${a.type} · Reliability ${a.reliability.toFixed(0)}/100`)}/><Industry title="REITs" icon={<TrendingUp/>} items={r.reits.map(a=>`${a.name} · ${a.strategy} · AUM $${Math.round(a.aum/1e6)}M`)}/></div>}
  {tab==='institutional'&&<div className="grid md:grid-cols-2 gap-3"><Card><h3 className="font-black flex gap-2"><Shield/>Finance & Risk</h3><div className="space-y-2 mt-3 text-xs">{r.mortgages.slice(-5).map(m=><div key={m.id} className="p-2 bg-zinc-950 rounded-xl">Mortgage · {m.lender} · Balance ${Math.round(m.remainingBalance).toLocaleString()} · {m.interestRateAnnual}%</div>)}{r.developmentFinancing.slice(-5).map(f=><div key={f.id} className="p-2 bg-zinc-950 rounded-xl">Development finance · {f.lender} · ${Math.round(f.amount).toLocaleString()} committed</div>)}</div></Card><Card><h3 className="font-black flex gap-2"><Scale/>Governance & Transactions</h3><div className="space-y-2 mt-3 text-xs">{r.permits.slice(-4).map(x=><div key={x.id} className="p-2 bg-zinc-950 rounded-xl">Permit · {x.type} · {x.status}</div>)}{r.inspections.slice(-4).map(x=><div key={x.id} className="p-2 bg-zinc-950 rounded-xl">Inspection · {x.type} · {x.status}</div>)}{r.constructionContracts.slice(-4).map(x=><div key={x.id} className="p-2 bg-zinc-950 rounded-xl">Construction contract · {Math.round(x.progress)}% complete</div>)}</div></Card></div>}
 </div>
}
const Card=({children}:{children:React.ReactNode})=><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4">{children}</div>;
const Metric=({label,value,icon}:{label:string;value:string;icon:React.ReactNode})=><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-3"><div className="flex justify-between text-zinc-500"><span className="text-[10px] font-bold uppercase">{label}</span>{icon}</div><div className="text-sm font-black text-zinc-100 mt-1">{value}</div></div>;
const Stat=({label,value}:{label:string;value:string})=><div><span className="text-zinc-500">{label}</span><div className="font-black text-zinc-200">{value}</div></div>;
const Input=({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:any)=>void;type?:string})=><label className="block"><span className="text-[10px] text-zinc-500 font-bold">{label}</span><input type={type} value={value} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-2 text-xs text-zinc-100"/></label>;
const Select=({value,onChange,options,labels}:{value:any;onChange:(v:any)=>void;options:string[];labels?:string[]})=><select value={value} onChange={e=>onChange(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-2 text-xs text-zinc-100">{options.map((o,i)=><option key={o} value={o}>{labels?.[i]||o||'Select'}</option>)}</select>;
const Industry=({title,items,icon}:{title:string;items:string[];icon:React.ReactNode})=><Card><h3 className="font-black flex items-center gap-2">{icon}{title}</h3><div className="space-y-2 mt-3">{items.map((x,i)=><div key={i} className="text-xs p-2 bg-zinc-950 rounded-xl text-zinc-300">{x}</div>)}</div></Card>;
