import React,{useMemo,useState} from 'react';
import {GameState,MarketplaceAssetItem} from '../../types';
import {getMarketplaceStores,ensureWorldMarketplace,purchaseWorldMarketplaceItem,sellWorldMarketplaceItem,useWorldPossession} from '../../engine/worldMarketplaceEngine';
import {ShoppingBag,Car,Plane,Ship,Watch,Shirt,Laptop,Sparkles,Search,MapPin,Store,ArrowUpRight,WalletCards,ChevronDown,Navigation,Users,Trash2} from 'lucide-react';

interface Props{state:GameState;onUpdateState?:(state:GameState)=>void}
const iconFor=(item:MarketplaceAssetItem)=>item.imageOrIcon==='Plane'?Plane:item.imageOrIcon==='Ship'?Ship:item.imageOrIcon==='Car'?Car:item.imageOrIcon==='Watch'?Watch:item.imageOrIcon==='Shirt'?Shirt:item.imageOrIcon==='Laptop'?Laptop:Sparkles;
export const LifeMarketplaceView:React.FC<Props>=({state,onUpdateState})=>{
 const [tab,setTab]=useState<'market'|'possessions'>('market'); const [storeId,setStoreId]=useState('all'); const [category,setCategory]=useState('All'); const [q,setQ]=useState(''); const [message,setMessage]=useState<string|null>(null); const [selected,setSelected]=useState<string|null>(null); const [guests,setGuests]=useState(1); const [destination,setDestination]=useState('Cape Town');
 ensureWorldMarketplace(state); const stores=getMarketplaceStores(); const items=state.lifeSystem?.marketplaceInventory||[]; const offers=items.filter(i=>!i.purchased); const owned=items.filter(i=>i.purchased);
 const filtered=useMemo(()=>offers.filter(i=>(storeId==='all'||i.storeId===storeId)&&(category==='All'||i.category===category)&&(!q||`${i.name} ${i.brand} ${i.storeName}`.toLowerCase().includes(q.toLowerCase()))),[offers,storeId,category,q]);
 const act=(fn:(s:GameState)=>{success:boolean;message:string})=>{const res=fn(state);setMessage(res.message);if(res.success)onUpdateState?.({...state});setTimeout(()=>setMessage(null),3000)};
 const purchase=(id:string)=>act(s=>purchaseWorldMarketplaceItem(s,id)); const sell=(id:string)=>act(s=>sellWorldMarketplaceItem(s,id));
 const use=(id:string,action:string)=>act(s=>useWorldPossession(s,id,action,guests,destination));
 const categories=['All','Vehicles','Fashion','Watches & Jewellery','Tech & Gadgets','Collectibles'];
 return <div className="space-y-4">
  {message&&<div className="sticky top-0 z-20 bg-emerald-950/95 border border-emerald-500/30 rounded-xl px-4 py-3 text-xs font-bold text-emerald-200 shadow-xl">{message}</div>}
  <div className="bg-zinc-900 rounded-2xl border border-zinc-800 p-5 space-y-4">
   <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><span className="text-[10px] uppercase tracking-widest font-black text-amber-400">World Commerce Exchange</span><h2 className="text-xl font-black">Marketplace & Possessions</h2><p className="text-xs text-zinc-400 mt-1">Fictional brands. Living stores. Ten fresh offers per store every simulation.</p></div><div className="flex gap-2"><button onClick={()=>setTab('market')} className={`px-3 py-2 rounded-xl text-xs font-black ${tab==='market'?'bg-amber-400 text-zinc-950':'bg-zinc-800 text-zinc-400'}`}>Marketplace</button><button onClick={()=>setTab('possessions')} className={`px-3 py-2 rounded-xl text-xs font-black ${tab==='possessions'?'bg-amber-400 text-zinc-950':'bg-zinc-800 text-zinc-400'}`}>My Possessions ({owned.length})</button></div></div>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs"><div className="bg-zinc-950 rounded-xl p-3"><div className="text-zinc-500">Cash</div><b className="text-emerald-400">${state.finances.cash.toLocaleString()}</b></div><div className="bg-zinc-950 rounded-xl p-3"><div className="text-zinc-500">Owned Items</div><b>{owned.length}</b></div><div className="bg-zinc-950 rounded-xl p-3"><div className="text-zinc-500">Offer Count</div><b>{offers.length}</b></div><div className="bg-zinc-950 rounded-xl p-3"><div className="text-zinc-500">Stores</div><b>{stores.length}</b></div></div>
  </div>
  {tab==='market'?<>
   <div className="flex flex-col gap-3 bg-zinc-900 border border-zinc-800 rounded-2xl p-3"><div className="flex gap-2 overflow-x-auto">{stores.map(s=><button key={s.id} onClick={()=>setStoreId(s.id)} className={`px-3 py-2 rounded-xl text-[11px] font-bold whitespace-nowrap ${storeId===s.id?'bg-zinc-700 text-amber-300':'bg-zinc-950 text-zinc-400'}`}><Store className="inline w-3 h-3 mr-1"/>{s.name}</button>)}<button onClick={()=>setStoreId('all')} className={`px-3 py-2 rounded-xl text-[11px] font-bold ${storeId==='all'?'bg-amber-400 text-zinc-950':'bg-zinc-950 text-zinc-400'}`}>All Stores</button></div><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`px-3 py-1.5 rounded-lg text-[10px] font-bold ${category===c?'border border-amber-400/50 text-amber-300 bg-amber-400/10':'bg-zinc-950 text-zinc-500'}`}>{c}</button>)}<div className="relative ml-auto"><Search className="absolute left-2 top-2 w-3 h-3 text-zinc-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search" className="bg-zinc-950 border border-zinc-800 rounded-lg pl-7 pr-3 py-1.5 text-[10px]"/></div></div></div>
   <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map(item=>{const I=iconFor(item);return <div key={item.id} className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 flex flex-col justify-between gap-4"><div><div className="flex justify-between"><div><span className="text-[9px] text-amber-400 font-black uppercase">{item.storeTier?.replace('_',' ')}</span><h3 className="font-black text-sm">{item.brand} {item.name.replace(item.brand+' ','')}</h3><div className="text-[10px] text-zinc-500"><MapPin className="inline w-3 h-3"/> {item.storeName}</div></div><I className="w-6 h-6 text-zinc-500"/></div><p className="text-[11px] text-zinc-400 mt-3">{item.description}</p><div className="grid grid-cols-2 gap-2 mt-3 text-[10px]"><div className="bg-zinc-950 rounded-lg p-2">Price<br/><b className="text-amber-300">${item.purchasePrice.toLocaleString()}</b></div><div className="bg-zinc-950 rounded-lg p-2">Resale<br/><b>${item.resaleValue.toLocaleString()}</b></div><div className="bg-zinc-950 rounded-lg p-2">Quality<br/><b>{item.qualityScore}/100</b></div><div className="bg-zinc-950 rounded-lg p-2">Prestige<br/><b>+{item.prestigeScore}</b></div></div></div><button onClick={()=>purchase(item.id)} className="w-full py-2 rounded-xl bg-amber-400 text-zinc-950 text-xs font-black hover:bg-amber-300">Acquire</button></div>})}</div>
  </>:<div className="space-y-3">{owned.map(item=>{const I=iconFor(item);const open=selected===item.id;return <div key={item.id} className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden"><button onClick={()=>setSelected(open?null:item.id)} className="w-full p-4 flex items-center justify-between text-left"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-zinc-950 flex items-center justify-center"><I className="w-5 h-5 text-amber-400"/></div><div><div className="text-[9px] uppercase text-zinc-500">{item.category}</div><b className="text-sm">{item.brand} {item.name.replace(item.brand+' ','')}</b><div className="text-[10px] text-zinc-500">Condition {item.condition||100}% · Usage {item.usageHours||0}h</div></div></div><ChevronDown className={`w-4 h-4 transition ${open?'rotate-180':''}`}/></button>{open&&<div className="border-t border-zinc-800 p-4 space-y-3"><div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-[10px]"><div>Current value<br/><b>${item.resaleValue.toLocaleString()}</b></div><div>Maintenance<br/><b>${item.monthlyMaintenance.toLocaleString()}/mo</b></div><div>Location<br/><b>{item.location||'Private storage'}</b></div><div>Capacity<br/><b>{item.passengerCapacity||'—'}</b></div></div>{(item.useActions||[]).length>0&&<div><div className="text-[10px] uppercase font-black text-zinc-500 mb-2">Interact</div><div className="flex flex-wrap gap-2">{item.useActions!.map(action=><button key={action} onClick={()=>use(item.id,action)} className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 rounded-xl text-[10px] font-bold">{action==='Take Flight'||action==='Go Cruising'?<Navigation className="inline w-3 h-3 mr-1"/>:action.includes('Guests')?<Users className="inline w-3 h-3 mr-1"/>:<ArrowUpRight className="inline w-3 h-3 mr-1"/>}{action}</button>)}</div>{(item.passengerCapacity||0)>0&&<div className="mt-2 flex items-center gap-2 text-[10px] text-zinc-400">Guests <input type="number" min="0" max={item.passengerCapacity} value={guests} onChange={e=>setGuests(Number(e.target.value))} className="w-16 bg-zinc-950 border border-zinc-800 rounded px-2 py-1"/></div>}<div className="mt-2 flex items-center gap-2 text-[10px] text-zinc-400">Destination <select value={destination} onChange={e=>setDestination(e.target.value)} className="bg-zinc-950 border border-zinc-800 rounded px-2 py-1"><option>Cape Town</option><option>Johannesburg</option><option>London</option><option>New York</option><option>Dubai</option><option>Paris</option><option>Singapore</option></select></div></div>}<button onClick={()=>sell(item.id)} className="text-red-300 text-[10px] font-bold"><Trash2 className="inline w-3 h-3 mr-1"/>Sell possession</button></div>}</div>})}{owned.length===0&&<div className="p-10 text-center bg-zinc-900 border border-zinc-800 rounded-2xl text-zinc-500">You do not own any marketplace possessions yet.</div>}</div>}
 </div>
};
