import React,{useState} from 'react';
import {GameState} from '../../types';
import {ensurePersonalManagement,hirePersonalStaff,firePersonalStaff,setPrimaryResidence,assignStaffToProperty,getPersonalStaffRoles,performPrimaryResidenceAction} from '../../engine/personalLifeManagementEngine';
import {BriefcaseBusiness,Home,UserPlus,Trash2,ShieldCheck} from 'lucide-react';
export const LifeAssetManagementView:React.FC<{state:GameState;onUpdateState?:(s:GameState)=>void}>=({state,onUpdateState})=>{const p=ensurePersonalManagement(state);const [msg,setMsg]=useState('');const act=(r:any)=>{setMsg(r.message);onUpdateState?.({...state});};const homes=state.finances.properties;const residence=homes.find(h=>h.id===p.primaryResidenceId);const rentals=homes.filter(h=>h.isRented);return <div className="space-y-4">
<div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5"><div className="flex justify-between"><div><div className="text-[10px] text-amber-400 font-black uppercase tracking-widest">Private Office & Estate</div><h2 className="text-xl font-black">My Assets & Personal Staff</h2><p className="text-xs text-zinc-500 mt-1">Control the homes you personally occupy, household services and staff who protect your wealth and time.</p></div><div className="text-right text-xs"><div>Staff payroll</div><b className="text-amber-300">${p.staffBudgetMonthly.toLocaleString()}/mo</b></div></div>{msg&&<div className="mt-3 p-3 rounded-xl bg-emerald-950/60 border border-emerald-500/30 text-xs text-emerald-200">{msg}</div>}</div>
<div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 space-y-3"><h3 className="font-black text-sm flex gap-2"><UserPlus className="w-4 h-4 text-amber-400"/>Household & Wealth Staff</h3><div className="grid grid-cols-2 gap-2">{getPersonalStaffRoles().map(r=><button key={r.id} onClick={()=>act(hirePersonalStaff(state,r.id))} className="text-left p-3 rounded-xl bg-zinc-950 border border-zinc-800 hover:border-amber-400/40"><div className="text-xs font-black">{r.label}</div><div className="text-[10px] text-zinc-500">${r.salary.toLocaleString()}/mo · {r.competence}% competence</div></button>)}</div></div>
<div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4 space-y-3"><h3 className="font-black text-sm"><Home className="inline w-4 h-4 text-amber-400 mr-1"/>Residences & Rentals</h3>{residence?<div className="p-3 rounded-xl bg-amber-400/10 border border-amber-400/20 text-xs"><b>{residence.name}</b><div className="text-zinc-400">Primary residence · {residence.city} · Condition {residence.condition}%</div><div className="flex flex-wrap gap-1.5 mt-2">{(['RENOVATE','SECURE','HOST','INSPECT','SELL'] as const).map(a=><button key={a} onClick={()=>act(performPrimaryResidenceAction(state,a))} className={`px-2 py-1 rounded-lg text-[9px] font-bold ${a==='SELL'?'bg-rose-950 text-rose-300':'bg-zinc-800 text-zinc-200'}`}>{a}</button>)}</div></div>:<div className="text-xs text-zinc-500">Choose one owned home as your primary residence.</div>}<div className="space-y-2">{homes.map(h=><div key={h.id} className="p-3 rounded-xl bg-zinc-950 border border-zinc-800 flex justify-between gap-2"><div><b className="text-xs">{h.name}</b><div className="text-[10px] text-zinc-500">{h.city} · {h.isRented?'Rental':'Personal/Available'}</div></div>{!h.isRented&&<button onClick={()=>act(setPrimaryResidence(state,h.id))} className="px-2 py-1 rounded-lg bg-zinc-800 text-[10px] font-bold">Live Here</button>}</div>)}</div><div className="text-[10px] text-emerald-400">Rental maintenance requirement: {rentals.length===0?0:Math.ceil(rentals.length/3)} workers for full coverage. Covered rentals can reach $0 maintenance.</div></div></div>
<div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-4"><h3 className="font-black text-sm mb-3"><BriefcaseBusiness className="inline w-4 h-4 text-amber-400 mr-1"/>Current Staff Roster</h3><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">{p.staff.filter(s=>s.active).map(s=><div key={s.id} className="p-3 rounded-xl bg-zinc-950 border border-zinc-800"><div className="flex justify-between"><b className="text-xs">{s.name}</b><button onClick={()=>act(firePersonalStaff(state,s.id))}><Trash2 className="w-3.5 h-3.5 text-rose-400"/></button></div><div className="text-[10px] text-amber-400">{s.role.replaceAll('_',' ')} · ${s.monthlySalary.toLocaleString()}/mo</div><div className="text-[10px] text-zinc-500">Competence {s.competence}% · Loyalty {s.loyalty}%</div>{s.role.includes('MAINTENANCE')&&rentals.length>0&&<button onClick={()=>rentals.slice(0,3).forEach(h=>assignStaffToProperty(state,s.id,h.id))} className="mt-2 w-full py-1.5 rounded-lg bg-zinc-800 text-[10px] font-bold"><ShieldCheck className="inline w-3 h-3 mr-1"/>Assign first rental properties</button>}</div>)}</div></div></div>}
