import { GameState, Company, CorporateCapitalMarketsState, CorporateAGM, CorporateResolutionVote, CorporateActivistCampaign, CorporateDebtInstrument, CorporateOffering, CorporateBankruptcyCase, CorporateAntitrustCase, CorporateGovernmentContract, CorporateLobbyingProgram, CorporateCorporateHistoryEvent } from '../types';
import { ensureCorporateSystemState } from './corporateSimulationEngine';
import { ensureCorporateDeepSimulationState } from './corporateDeepSimulationEngine';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.max(0,Math.round(v));
function company(state:GameState,id:string){ return state.companies.find(c=>c.id===id); }
function addHistory(state:GameState, event:CorporateCorporateHistoryEvent){ const s=ensureCorporateCapitalMarketsState(state); s.history.unshift(event); s.history=s.history.slice(0,500); }
function ensureCompanyFields(c:Company){ c.cashReserve??=c.cash??0; c.debt??=0; c.totalAssets??=Math.max(c.fixedAssets||0,c.cashReserve||0); c.totalLiabilities??=c.debt||0; c.creditRating??='BBB'; c.corporateTaxRate??=27; c.publicFloatShares??=Math.round(c.totalShares*.65); c.insiderShares??=Math.round(c.totalShares*.15); c.institutionalShares??=Math.max(0,c.totalShares-c.publicFloatShares-c.insiderShares); }

export function initializeCorporateCapitalMarketsState(): CorporateCapitalMarketsState { return {
 version:1, agms:[], resolutions:[], activistCampaigns:[], debtInstruments:[], offerings:[], bankruptcyCases:[], antitrustCases:[], governmentContracts:[], lobbyingPrograms:[], history:[], maBids:[], ceoCompensation:{}, lastProcessedTick:-1
}; }
export function ensureCorporateCapitalMarketsState(state:GameState):CorporateCapitalMarketsState { if(!state.corporateCapitalMarkets) state.corporateCapitalMarkets=initializeCorporateCapitalMarketsState(); const s=state.corporateCapitalMarkets; s.version??=1; s.agms??=[]; s.resolutions??=[]; s.activistCampaigns??=[]; s.debtInstruments??=[]; s.offerings??=[]; s.bankruptcyCases??=[]; s.antitrustCases??=[]; s.governmentContracts??=[]; s.lobbyingPrograms??=[]; s.history??=[]; s.maBids??=[]; s.ceoCompensation??={}; s.lastProcessedTick??=-1; return s; }

function shareholderVotes(state:GameState, c:Company, required:number, type:string){
 const deep=ensureCorporateDeepSimulationState(state); const corp=ensureCorporateSystemState(state); const records=corp.shareholderRecords[c.id]||[]; let forVotes=0, against=0;
 for(const r of records){ if(r.shares<=0) continue; let support=50; const inst=deep.institutionalInvestors.find(i=>i.id===r.holderId); if(inst){ if(inst.mandate==='ACTIVIST') support= type==='RESTRUCTURE'||type==='FIRE_CEO'?72:48; if(inst.mandate==='INCOME') support=type==='DIVIDEND'?82:55; if(inst.mandate==='GROWTH') support=type==='CAPEX'||type==='BYLAW_CHANGE'?72:52; if(inst.mandate==='VALUE') support=type==='DEBT_ISSUANCE'?42:62; if(inst.mandate==='SOVEREIGN') support=58; } else if(r.holderId==='player') support=65; else if(r.holderType==='FOUNDER') support=58; else support=50; const votes=r.votingPowerPercent; if(support>=50) forVotes+=votes*(support/100); else against+=votes*((100-support)/100); }
 return {forVotes,against,passed:forVotes>=required};
}

export function conveneAGM(state:GameState, companyId:string):{success:boolean;message:string;agm?:CorporateAGM}{
 const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; const s=ensureCorporateCapitalMarketsState(state); const last=s.agms.filter(a=>a.companyId===companyId).sort((a,b)=>b.scheduledTick-a.scheduledTick)[0]; const resolutions=s.resolutions.filter(r=>r.companyId===companyId&&(!last||r.createdTick>last.scheduledTick)); const votes:CorporateResolutionVote[]=[]; for(const r of resolutions){ const v=shareholderVotes(state,c,r.requiredMajority,r.type); r.votesFor=v.forVotes; r.votesAgainst=v.against; r.status=v.passed?'PASSED':'FAILED'; votes.push({resolutionId:r.id,forVotes:v.forVotes,againstVotes:v.against,supportPercent:v.forVotes/(v.forVotes+v.against||1)*100,passed:v.passed}); }
 const board=ensureCorporateSystemState(state).boardSeats[companyId]||[]; const boardSupport=board.reduce((sum,b)=>sum+b.representedOwnershipPercent*(b.supportLevel/100),0); const agm:CorporateAGM={id:`agm_${state.simulationTick}_${companyId}`,companyId,scheduledTick:state.simulationTick,attendeeParticipation:clamp(55+(c.institutionalShares||0)/Math.max(1,c.totalShares)*20),shareholderTurnoutPercent:clamp(60+(c.institutionalShares||0)/Math.max(1,c.totalShares)*20),resolutions:votes,ceoEvaluation:clamp((c.ceoApprovalRating||65)+((c.monthlyNetProfit>0)?8:-12)),boardElectionOccurred:board.length>0,boardSupportPercent:boardSupport}; s.agms.push(agm); addHistory(state,{id:`hist_${Date.now()}_agm`,tick:state.simulationTick,companyId,type:'AGM',title:`Annual general meeting held at ${c.name}`,description:`Shareholders voted on ${votes.length} pending resolution(s).`,impact:votes.filter(v=>v.passed).length}); return {success:true,message:`AGM completed for ${c.name}: ${votes.filter(v=>v.passed).length}/${votes.length} resolutions passed.`,agm}; }

export function createCEOCompensationPackage(state:GameState,companyId:string,baseSalary:number,bonusPercent:number,optionShares:number,strikePrice?:number){ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; const s=ensureCorporateCapitalMarketsState(state); const price=strikePrice??c.sharePrice; const pkg=s.ceoCompensation[companyId]={baseSalary:money(baseSalary),targetBonusPercent:clamp(bonusPercent,0,100),optionShares:Math.max(0,Math.floor(optionShares)),strikePrice:price,vestedOptions:0,vestingMonthsRemaining:36,lastReviewTick:state.simulationTick}; addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'CEO_COMPENSATION',title:`CEO compensation package approved`,description:`Base salary $${pkg.baseSalary.toLocaleString()}, target bonus ${pkg.targetBonusPercent}%, ${pkg.optionShares.toLocaleString()} options at $${pkg.strikePrice.toFixed(2)} strike.`,impact:0}); return {success:true,message:`CEO compensation package set for ${c.name}.`}; }

export function launchActivistCampaign(state:GameState,companyId:string,institutionId='inst_atlas_activist',demand='Improve capital allocation and shareholder returns'): {success:boolean;message:string;campaign?:CorporateActivistCampaign}{ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; const s=ensureCorporateCapitalMarketsState(state); const existing=s.activistCampaigns.find(a=>a.companyId===companyId&&a.status==='ACTIVE'); if(existing) return {success:false,message:'An activist campaign is already active.'}; const campaign:CorporateActivistCampaign={id:`activist_${Date.now()}`,companyId,institutionId,demand,ownershipPercent:Math.max(.5,(c.institutionalShares||0)/Math.max(1,c.totalShares)*8),supportPercent:clamp(35+(100-(c.ceoApprovalRating||65))*.4),stage:'PRIVATE_ENGAGEMENT',status:'ACTIVE',createdTick:state.simulationTick}; s.activistCampaigns.push(campaign); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'ACTIVISM',title:`Activist campaign launched at ${c.name}`,description:demand,impact:-1}); return {success:true,message:`Activist campaign launched against ${c.name}.`,campaign}; }

export function issueCorporateDebt(state:GameState,companyId:string,principal:number,maturityMonths=36,couponRate?:number){ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; ensureCompanyFields(c); const s=ensureCorporateCapitalMarketsState(state); const rate=couponRate??Math.max(3,ensureCorporateDeepSimulationState(state).policyRate+ensureCorporateDeepSimulationState(state).creditSpread+(c.creditRating==='BBB'?1:0)); const amount=money(principal); if(amount<100000) return {success:false,message:'Debt issuance is too small.'}; c.cashReserve+=amount; c.debt=(c.debt||0)+amount; const d:CorporateDebtInstrument={id:`bond_${Date.now()}`,companyId,principal:amount,outstanding:amount,couponRate:rate,maturityTick:state.simulationTick+maturityMonths,seniority:'SENIOR_UNSECURED',creditRating:c.creditRating||'BBB',issuedTick:state.simulationTick}; s.debtInstruments.push(d); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'DEBT',title:`${c.name} issued corporate debt`,description:`Raised $${amount.toLocaleString()} at ${rate.toFixed(2)}% coupon.`,impact:amount}); return {success:true,message:`${c.name} raised $${amount.toLocaleString()} in debt at ${rate.toFixed(2)}%.`}; }

export function launchSecondaryOffering(state:GameState,companyId:string,newShares:number,discountPercent=0){ const c=company(state,companyId); if(!c||!c.isPublic) return {success:false,message:'A public company is required.'}; const s=ensureCorporateCapitalMarketsState(state); const n=Math.max(1,Math.floor(newShares)); const price=Math.max(.5,c.sharePrice*(1-clamp(discountPercent,0,25)/100)); const o:CorporateOffering={id:`offer_${Date.now()}`,companyId,type:'SECONDARY',sharesOffered:n,offerPrice:price,proceeds:money(n*price),stage:'OPEN',createdTick:state.simulationTick,remainingShares:n}; s.offerings.push(o); return {success:true,message:`Secondary offering opened for ${c.name}: ${n.toLocaleString()} shares at $${price.toFixed(2)}.`}; }
export function launchIPO(state:GameState,companyId:string,sharesOffered:number,offerPrice:number){ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; if(c.isPublic) return {success:false,message:'Company is already public.'}; const s=ensureCorporateCapitalMarketsState(state); const n=Math.max(1000,Math.floor(sharesOffered)); c.isPublic=true; c.totalShares=Math.max(1,c.totalShares||n); c.publicFloatShares=n; c.insiderShares=Math.max(0,c.totalShares-n); c.sharePrice=offerPrice; c.valuation=c.totalShares*offerPrice; const o:CorporateOffering={id:`ipo_${Date.now()}`,companyId,type:'IPO',sharesOffered:n,offerPrice,proceeds:money(n*offerPrice),stage:'PRICED',createdTick:state.simulationTick,remainingShares:n}; s.offerings.push(o); ensureCorporateSystemState(state).publicCompanyIds=Array.from(new Set([...ensureCorporateSystemState(state).publicCompanyIds,c.id])); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'IPO',title:`${c.name} completed an IPO`,description:`${n.toLocaleString()} shares were offered at $${offerPrice.toFixed(2)}.`,impact:o.proceeds}); return {success:true,message:`${c.name} is now publicly listed.`}; }

export function launchCrossBorderMABid(state:GameState,bidderCompanyId:string,targetCompanyId:string,premiumPercent=30){ const bidder=company(state,bidderCompanyId), target=company(state,targetCompanyId); if(!bidder||!target) return {success:false,message:'Bidder and target are required.'}; if(bidder.country===target.country) return {success:false,message:'This transaction is domestic; select companies in different countries.'}; const s=ensureCorporateCapitalMarketsState(state); const deep=ensureCorporateDeepSimulationState(state); const premium=Math.max(15,Math.min(65,premiumPercent)); const fxRate=1; const treatyFriction=clamp((deep.tradeStress||20)*.5 + 15); const antitrustRisk=clamp((bidder.marketShare||0)*1.4+(target.marketShare||0)*1.8+treatyFriction*.35); const bid: any={id:`xma_${Date.now()}_${bidder.id}_${target.id}`,bidderCompanyId:bidder.id,targetCompanyId:target.id,bidderName:bidder.name,targetName:target.name,bidValue:money(target.valuation*(1+premium/100)),premiumPercent:premium,financingRatio:.5,expectedSynergyPercent:Math.max(2,Math.min(20,8+(bidder.sector===target.sector?4:0))),integrationRisk:clamp(25+(target.employeesCount/Math.max(1,bidder.employeesCount))*20),antitrustRisk,politicalRisk:clamp(treatyFriction+((deep.regulatoryProfiles[target.id]?.politicalAttention)||30)*.45),shareholderSupport:0,stage:'RUMOR',createdTick:state.simulationTick,notes:[`Cross-border transaction: ${bidder.country} → ${target.country}`,`Treaty/trade friction ${treatyFriction.toFixed(0)}`],crossBorder:true,bidderCountry:bidder.country,targetCountry:target.country,fxRate,treatyFriction}; s.history.push({id:`hist_${Date.now()}`,tick:state.simulationTick,companyId:bidder.id,type:'M_AND_A',title:`Cross-border acquisition proposed`,description:`${bidder.name} proposed acquiring ${target.name} across jurisdictions.`,impact:-antitrustRisk}); s.maBids.push(bid); return {success:true,message:`Cross-border M&A proposal launched: ${bidder.name} → ${target.name}.`}; }

export function openAntitrustCase(state:GameState,companyId:string,reason='Market concentration'): {success:boolean;message:string}{ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; const s=ensureCorporateCapitalMarketsState(state); const existing=s.antitrustCases.find(x=>x.companyId===companyId&&x.status==='OPEN'); if(existing) return {success:false,message:'An antitrust case is already open.'}; const d=ensureCorporateDeepSimulationState(state).regulatoryProfiles[companyId]; const risk=clamp((d?.antitrustExposure||c.marketShare*2)+10); const a:CorporateAntitrustCase={id:`anti_${Date.now()}`,companyId,authority:'Competition Authority',jurisdiction:c.country,reason,risk,stage:'INVESTIGATION',status:'OPEN',fineExposure:money(c.monthlyRevenue*Math.max(.02,risk/100*.15)),createdTick:state.simulationTick}; s.antitrustCases.push(a); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'ANTITRUST',title:`Antitrust investigation opened`,description:`${reason} in ${c.country}.`,impact:-risk}); return {success:true,message:`Antitrust investigation opened for ${c.name}.`}; }

export function submitGovernmentContractBid(state:GameState,companyId:string,agency:string,value:number,durationMonths=12){ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; const s=ensureCorporateCapitalMarketsState(state); const quality=(c.productQuality+c.brandReputation+c.employeeProductivity)/3; const probability=clamp(30+quality*.5-(c.debt||0)/Math.max(1,c.totalAssets||1)*15); const awarded=probability>55; const contract:CorporateGovernmentContract={id:`gov_${Date.now()}`,companyId,agency,jurisdiction:c.country,contractValue:money(value),durationMonths,stage:awarded?'AWARDED':'BID_SUBMITTED',performanceScore:quality,awardProbability:probability,createdTick:state.simulationTick,remainingMonths:durationMonths}; s.governmentContracts.push(contract); if(awarded) addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'GOVERNMENT_CONTRACT',title:`Government contract awarded`,description:`${agency} awarded ${c.name} a $${money(value).toLocaleString()} contract.`,impact:value}); return {success:true,message:awarded?`${c.name} won a $${money(value).toLocaleString()} government contract.`:`${c.name} submitted a government contract bid but was not selected.`}; }

export function startCorporateLobbying(state:GameState,companyId:string,monthlyBudget:number,issue='Business and regulatory policy'){ const c=company(state,companyId); if(!c) return {success:false,message:'Company not found.'}; ensureCompanyFields(c); const amount=money(monthlyBudget); if(amount<=0||c.cashReserve<amount) return {success:false,message:'Company lacks the cash for this lobbying budget.'}; const s=ensureCorporateCapitalMarketsState(state); c.cashReserve-=amount; const p:CorporateLobbyingProgram={id:`lobby_${Date.now()}`,companyId,issue,monthlyBudget:amount,influence:clamp(Math.sqrt(amount)/1000),jurisdiction:c.country,status:'ACTIVE',createdTick:state.simulationTick}; s.lobbyingPrograms.push(p); const deep=ensureCorporateDeepSimulationState(state); const reg=deep.regulatoryProfiles[companyId]; if(reg) reg.lobbyingInfluence=clamp(reg.lobbyingInfluence+p.influence); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId,type:'LOBBYING',title:`Corporate government-relations program expanded`,description:`${issue}; monthly budget $${amount.toLocaleString()}.`,impact:p.influence}); return {success:true,message:`${c.name} began a lawful government-relations program.`}; }

function bankruptcyStep(state:GameState,s:CorporateCapitalMarketsState,news:string[]){ for(const c of state.companies.filter(x=>x.isPublic)){ ensureCompanyFields(c); const debtService=s.debtInstruments.filter(d=>d.companyId===c.id&&d.outstanding>0).reduce((sum,d)=>sum+d.outstanding*d.couponRate/100/12,0); const distress=(c.cashReserve<=0&&c.monthlyNetProfit<0)||(c.totalLiabilities||0)>Math.max(1,(c.totalAssets||0)*1.15)||debtService>Math.max(1,c.monthlyRevenue*.25); let b=s.bankruptcyCases.find(x=>x.companyId===c.id&&x.status!=='EXITED'); if(distress&&!b){ b={id:`bank_${Date.now()}_${c.id}`,companyId:c.id,stage:'EARLY_DISTRESS',status:'ACTIVE',cashAtFiling:c.cashReserve||0,debtAtFiling:c.debt||0,restructuringPlan:'NEGOTIATE',creditorRecoveryEstimate:35,createdTick:state.simulationTick}; s.bankruptcyCases.push(b); news.push(`${c.name} entered early financial distress.`); addHistory(state,{id:`hist_${Date.now()}`,tick:state.simulationTick,companyId:c.id,type:'BANKRUPTCY',title:`${c.name} entered financial distress`,description:'Liquidity and leverage triggered a restructuring process.',impact:-20}); }
 if(b){ if(c.cashReserve>c.monthlyRevenue*.5&&c.monthlyNetProfit>0){ b.status='EXITED'; b.stage='EMERGENCE'; c.creditRating='BB'; news.push(`${c.name} emerged from restructuring.`); } else { b.stage=b.stage==='EARLY_DISTRESS'?'RESTRUCTURING':b.stage==='RESTRUCTURING'?'CREDITOR_VOTE':'LIQUIDATION_RISK'; if(b.stage==='LIQUIDATION_RISK'&&c.cashReserve<=0&&c.monthlyNetProfit<0){ c.isPublic=false; c.publicFloatShares=0; news.push(`${c.name} entered liquidation risk after failing to restore liquidity.`); } } }
 }}

function processActivism(state:GameState,s:CorporateCapitalMarketsState,news:string[]){ for(const a of s.activistCampaigns.filter(x=>x.status==='ACTIVE')){ const c=company(state,a.companyId); if(!c) continue; const g=ensureCorporateDeepSimulationState(state).governanceProfiles[c.id]; if(!g) continue; a.supportPercent=clamp(a.supportPercent + (c.monthlyNetProfit<0?4:-1) + (g.ceoConfidence<50?3:0)); if(a.supportPercent>68&&a.stage==='PRIVATE_ENGAGEMENT'){a.stage='PUBLIC_CAMPAIGN'; news.push(`${c.name} faces a public activist campaign.`);} if(a.supportPercent>82&&a.stage==='PUBLIC_CAMPAIGN'){a.stage='PROXY_SOLICITATION';} if(a.stage==='PROXY_SOLICITATION'&&a.supportPercent>90){a.stage='SETTLEMENT'; a.status='SETTLED'; g.strategy='COST_DISCIPLINE'; g.boardConfidence=clamp(g.boardConfidence-4); news.push(`${c.name} reached a settlement with activist shareholders.`);} }}

function processDebtAndOfferings(state:GameState,s:CorporateCapitalMarketsState,news:string[]){ for(const d of s.debtInstruments){ if(d.outstanding<=0) continue; const c=company(state,d.companyId); if(!c) continue; if(state.simulationTick>=d.maturityTick){ if((c.cashReserve||0)>=d.outstanding){c.cashReserve-=d.outstanding;c.debt=Math.max(0,(c.debt||0)-d.outstanding);d.outstanding=0;news.push(`${c.name} repaid a maturing debt instrument.`);} else {c.creditRating='CCC';news.push(`${c.name} could not fully repay maturing debt and faces refinancing pressure.`);} }} for(const o of s.offerings.filter(x=>x.stage==='OPEN')){ const c=company(state,o.companyId); if(!c) continue; const demand=Math.min(o.remainingShares,Math.floor(o.sharesOffered*(.35+((c.employeeMorale||60)/100)*.35))); const proceeds=money(demand*o.offerPrice); if(demand>0){o.remainingShares-=demand;c.cashReserve=(c.cashReserve||0)+proceeds;c.totalShares+=demand;c.publicFloatShares=(c.publicFloatShares||0)+demand;} if(o.remainingShares<=0||state.simulationTick-o.createdTick>=3){o.stage=o.remainingShares<=0?'CLOSED':'WITHDRAWN'; if(o.stage==='CLOSED') news.push(`${c.name} completed a ${o.type.toLowerCase()} share offering.`);} }}

function processContracts(state:GameState,s:CorporateCapitalMarketsState,news:string[]){ for(const x of s.governmentContracts.filter(x=>x.stage==='AWARDED'&&x.remainingMonths>0)){ const c=company(state,x.companyId); if(!c) continue; const monthly=x.contractValue/x.durationMonths; c.monthlyRevenue+=monthly*.55; c.cashReserve+=monthly*.12; x.remainingMonths--; x.performanceScore=clamp(x.performanceScore+(c.employeeProductivity-60)*.02); if(x.performanceScore<40){x.stage='BREACH';news.push(`${c.name} is at risk of breaching a government contract.`);} else if(x.remainingMonths<=0){x.stage='COMPLETED';news.push(`${c.name} completed a government contract.`);} }}

function processLobbying(state:GameState,s:CorporateCapitalMarketsState){ const deep=ensureCorporateDeepSimulationState(state); for(const p of s.lobbyingPrograms.filter(x=>x.status==='ACTIVE')){ const c=company(state,p.companyId); if(!c) continue; if(c.cashReserve>=p.monthlyBudget){c.cashReserve-=p.monthlyBudget; const r=deep.regulatoryProfiles[c.id]; if(r){r.lobbyingInfluence=clamp(r.lobbyingInfluence+p.influence*.12);r.politicalAttention=clamp(r.politicalAttention-p.influence*.08);} } else p.status='SUSPENDED'; }}

export function simulateCorporateCapitalMarkets(state:GameState,news:string[]=[]){ const s=ensureCorporateCapitalMarketsState(state); if(s.lastProcessedTick===state.simulationTick) return; if(state.simulationTick>0&&state.simulationTick%12===0){ for(const c of state.companies.filter(x=>x.isPublic)) conveneAGM(state,c.id); } processActivism(state,s,news); processDebtAndOfferings(state,s,news); processContracts(state,s,news); processLobbying(state,s); bankruptcyStep(state,s,news); for(const c of state.companies.filter(x=>x.isPublic)){ const pkg=s.ceoCompensation[c.id]; if(pkg){ const ceo=c.executives.find(e=>e.role==='CEO'); if(ceo){const perf=clamp((c.monthlyNetProfit>0?65:35)+(c.employeeProductivity-60)*.4); ceo.salaryMonthly=pkg.baseSalary*(1+(perf/100)*pkg.targetBonusPercent/100); pkg.vestedOptions=Math.min(pkg.optionShares,pkg.vestedOptions+Math.floor(pkg.optionShares/36)); pkg.vestingMonthsRemaining=Math.max(0,pkg.vestingMonthsRemaining-1); }} } s.lastProcessedTick=state.simulationTick; }
