import { GameState, Company, CorporateDepartmentType } from '../types';

const departments:CorporateDepartmentType[]=['OPERATIONS','PRODUCTION','MARKETING','HUMAN_RESOURCES','ADMINISTRATION','RESEARCH_DEVELOPMENT','SALES','FINANCE'];
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const tick=(s:GameState)=>s.simulationTick;

type WorkforceStatus='ACTIVE'|'ON_LEAVE'|'NOTICE'|'TERMINATED';
export interface CorporateEmployeeRecord { id:string; npcId:string; name:string; companyId:string; department:CorporateDepartmentType; title:string; managerNpcId?:string; salaryMonthly:number; skillScore:number; performance:number; potential:number; morale:number; engagement:number; yearsAtCompany:number; yearsInRole:number; promotionReadiness:number; status:WorkforceStatus; lastReviewTick:number; }
export interface WorkforceEvent { tick:number; type:string; npcId?:string; companyId:string; narrative:string; }
export interface DepartmentManagementState { department:CorporateDepartmentType; headNpcId?:string; managerNpcIds:string[]; employeeNpcIds:string[]; budget:number; targetHeadcount:number; morale:number; productivity:number; turnoverRate:number; }
export interface SuccessionCandidate { npcId:string; name:string; role:string; readiness:number; competence:number; loyalty:number; risk:number; }
export interface CorporateWorkforceState { version:number; employees:Record<string,CorporateEmployeeRecord>; departments:Record<string,Record<CorporateDepartmentType,DepartmentManagementState>>; events:WorkforceEvent[]; succession:Record<string,SuccessionCandidate[]>; laborRelations:Record<string,{unionPressure:number;disputeRisk:number;strikeRisk:number;openDisputes:string[]}>; lastProcessedTick:number; }

function findNpc(s:GameState,id:string){return s.livingWorld?.npcs?.find(n=>n.id===id);}
function name(n:any){return `${n.firstName} ${n.lastName}`;}
function canManage(s:GameState,c:Company){const o=s.politics.currentOffice; return c.playerOwnershipPercentage>=51 || c.executives?.some(e=>e.npcId===s.character.id&&['CEO','COO','CHRO'].includes(e.role)) || !!(o?.inOffice&&/President|Minister/.test(o.title));}
function ensureState(s:GameState):CorporateWorkforceState{const cm=s.corporateManagement!; const holder=cm as CorporateManagementStateExtended; holder.workforce??=createState(s); return holder.workforce;}
interface CorporateManagementStateExtended {workforce?:CorporateWorkforceState}
function createState(s:GameState):CorporateWorkforceState{return{version:1,employees:{},departments:{},events:[],succession:{},laborRelations:{},lastProcessedTick:-1};}
function ensureCompany(s:GameState,c:Company){const st=ensureState(s);st.departments[c.id]??={} as Record<CorporateDepartmentType,DepartmentManagementState>;const byDept=st.departments[c.id];for(const d of departments){byDept[d]??={department:d,managerNpcIds:[],employeeNpcIds:[],budget:0,targetHeadcount:0,morale:c.employeeMorale||70,productivity:c.employeeProductivity||60,turnoverRate:.08};}st.laborRelations[c.id]??={unionPressure:15,disputeRisk:10,strikeRisk:3,openDisputes:[]};return byDept;}

export function initializeCorporateWorkforce(state:GameState){if(!state.corporateManagement) throw new Error('Corporate management state must be initialized first.');state.companies.forEach(c=>ensureCompany(state,c));return ensureState(state);}

export function recruitNpcEmployee(state:GameState,companyId:string,npcId:string,department:CorporateDepartmentType,titleName='Employee',salary?:number){const c=state.companies.find(x=>x.id===companyId);const n=findNpc(state,npcId);if(!c||!n)return{success:false,message:'Company or NPC not found.'};if(!canManage(state,c))return{success:false,message:'Workforce management authority required.'};if(n.career?.employerCompanyId&&n.career.employerCompanyId!==companyId)return{success:false,message:'NPC is already employed elsewhere.'};const st=ensureState(state);if(st.employees[`${companyId}:${npcId}`])return{success:false,message:'NPC is already on this workforce roster.'};const skill=clamp(Math.round(((n.skills?.management||50)+(n.skills?.technical||50)+(n.skills?.finance||50)+(n.skills?.negotiation||50))/4));const rec:CorporateEmployeeRecord={id:`emp_${companyId}_${npcId}`,npcId,name:name(n),companyId,department,title:titleName, salaryMonthly:Math.round(salary??Math.max(2500,skill*90)),skillScore:skill,performance:clamp(55+skill*.25),potential:clamp(skill+((n.skills?.management||50)+(n.skills?.technical||50))*.1),morale:72,engagement:70,yearsAtCompany:0,yearsInRole:0,promotionReadiness:clamp(skill*.7),status:'ACTIVE',lastReviewTick:tick(state)};st.employees[rec.id]=rec;ensureCompany(state,c)[department].employeeNpcIds.push(npcId);n.career={...(n.career||{occupation:titleName,field:c.industry,monthlySalary:rec.salaryMonthly,employerName:c.name,yearsInRole:0,careerTier:'Entry'}),occupation:titleName,field:c.industry,monthlySalary:rec.salaryMonthly,employerName:c.name,employerCompanyId:c.id,careerTier:skill>80?'Senior':skill>60?'Mid':'Entry'};c.employeesCount++;state.corporateManagement!.history.unshift({tick:tick(state),companyId,type:'NPC_RECRUITMENT',summary:`${rec.name} joined ${c.name} in ${department}.`});return{success:true,message:`${rec.name} recruited into ${department}.`,employee:rec};}

export function promoteCorporateEmployee(state:GameState,companyId:string,employeeId:string,newTitle:string,newDepartment?:CorporateDepartmentType){const c=state.companies.find(x=>x.id===companyId);const st=ensureState(state);const e=st.employees[employeeId];if(!c||!e)return{success:false,message:'Employee not found.'};if(!canManage(state,c))return{success:false,message:'Promotion authority required.'};if(e.performance<60||e.promotionReadiness<55)return{success:false,message:'Employee is not yet ready for promotion.'};const old=e.department;e.title=newTitle;e.department=newDepartment||old;e.yearsInRole=0;e.promotionReadiness=25;e.salaryMonthly=Math.round(e.salaryMonthly*1.12);if(old!==e.department){ensureCompany(state,c)[old].employeeNpcIds=ensureCompany(state,c)[old].employeeNpcIds.filter(id=>id!==e.npcId);ensureCompany(state,c)[e.department].employeeNpcIds.push(e.npcId);}const n=findNpc(state,e.npcId);if(n?.career){n.career.occupation=newTitle;n.career.monthlySalary=e.salaryMonthly;n.career.careerTier='Senior';n.career.yearsInRole=0;}st.events.unshift({tick:tick(state),type:'PROMOTION',npcId:e.npcId,companyId,narrative:`${e.name} was promoted to ${newTitle}.`});return{success:true,message:`${e.name} promoted to ${newTitle}.`};}

export function terminateCorporateEmployee(state:GameState,companyId:string,employeeId:string,reason='Performance'){const c=state.companies.find(x=>x.id===companyId);const st=ensureState(state);const e=st.employees[employeeId];if(!c||!e)return{success:false,message:'Employee not found.'};if(!canManage(state,c))return{success:false,message:'Termination authority required.'};e.status='TERMINATED';const d=ensureCompany(state,c)[e.department];d.employeeNpcIds=d.employeeNpcIds.filter(id=>id!==e.npcId);c.employeesCount=Math.max(0,c.employeesCount-1);const n=findNpc(state,e.npcId);if(n?.career?.employerCompanyId===c.id){n.career={...n.career,employerCompanyId:undefined,employerName:'Unemployed',occupation:'Seeking Employment',monthlySalary:0};}st.events.unshift({tick:tick(state),type:'TERMINATION',npcId:e.npcId,companyId,narrative:`${e.name} was terminated. Reason: ${reason}.`});return{success:true,message:`${e.name} terminated.`};}

export function conductCorporatePerformanceReview(state:GameState,companyId:string,employeeId:string,performanceDelta:number){const st=ensureState(state);const e=st.employees[employeeId];const c=state.companies.find(x=>x.id===companyId);if(!e||!c)return{success:false,message:'Employee not found.'};e.performance=clamp(e.performance+performanceDelta);e.promotionReadiness=clamp(e.promotionReadiness+(e.performance-60)*.08);e.lastReviewTick=tick(state);return{success:true,message:`Performance review recorded for ${e.name}.`};}

export function nominateExecutiveSuccessor(state:GameState,companyId:string,role:string){const c=state.companies.find(x=>x.id===companyId);if(!c)return{success:false,message:'Company not found.'};const st=ensureState(state);const candidates=Object.values(st.employees).filter(e=>e.companyId===companyId&&e.status==='ACTIVE').map(e=>({npcId:e.npcId,name:e.name,role:e.title,readiness:clamp(e.promotionReadiness+e.performance*.35),competence:e.skillScore,loyalty:e.engagement,risk:clamp(100-e.morale)})).sort((a,b)=>b.readiness-a.readiness).slice(0,8);st.succession[`${companyId}:${role}`]=candidates;return{success:true,message:`Succession slate prepared for ${role}.`,candidates};}

export function simulateCorporateWorkforceMonthly(state:GameState,news:string[]=[]){const st=ensureState(state);if(st.lastProcessedTick===tick(state))return;for(const c of state.companies){const byDept=ensureCompany(state,c);const roster=Object.values(st.employees).filter(e=>e.companyId===c.id&&e.status==='ACTIVE');for(const e of roster){e.yearsAtCompany+=1/12;e.yearsInRole+=1/12;const managerBonus=e.managerNpcId?3:0;e.performance=clamp(e.performance+(e.morale-50)*.015+(e.engagement-50)*.01+managerBonus*.01);e.promotionReadiness=clamp(e.promotionReadiness+(e.performance>70?.8:.2));e.morale=clamp(e.morale+(c.employeeMorale-e.morale)*.05);e.engagement=clamp(e.engagement+(c.employeeMorale-e.engagement)*.03);if(e.performance<40&&Math.random()<.04)e.status='NOTICE';if(e.status==='NOTICE'&&Math.random()<.15){e.status='TERMINATED';c.employeesCount=Math.max(0,c.employeesCount-1);news.push(`${e.name} resigned from ${c.name} after a prolonged performance and morale decline.`);}}
    const labor=st.laborRelations[c.id];const avgMorale=roster.reduce((a,e)=>a+e.morale,0)/Math.max(1,roster.length);labor.disputeRisk=clamp(labor.disputeRisk+(55-avgMorale)*.04+(c.averageEmployeeSalary<1000?2:0));labor.strikeRisk=clamp(labor.disputeRisk*.25+labor.unionPressure*.08);if(labor.strikeRisk>45&&Math.random()<.08){labor.openDisputes.push(`Labor dispute at tick ${tick(state)}`);news.push(`Labor dispute escalated at ${c.name}.`);c.employeeProductivity=clamp(c.employeeProductivity-3);}
    departments.forEach(d=>{const dept=byDept[d];dept.morale=clamp(dept.morale+(avgMorale-dept.morale)*.08);dept.productivity=clamp(dept.productivity+(c.employeeProductivity-dept.productivity)*.05);dept.targetHeadcount=Math.max(dept.targetHeadcount,dept.employeeNpcIds.length);});
    const managers=roster.filter(e=>/Manager|Director|Head|Chief|Vice President/i.test(e.title));for(const m of managers){m.performance=clamp(m.performance+(roster.filter(e=>e.managerNpcId===m.npcId).reduce((a,e)=>a+e.performance,0)/Math.max(1,roster.filter(e=>e.managerNpcId===m.npcId).length-50)*.01));}
  }st.lastProcessedTick=tick(state);}
