import { GameState, Company, CorporateManagementState, CompanyManagementPermission, CorporateDepartmentType, CorporateLoanApplication } from '../types';
import { EXPANSION2_BANKS } from '../data/expansion2Catalogs';
import { recordFinancialTransaction } from './financialLedgerEngine';

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number)=>Math.max(0,Math.round(v));

function ensure(state:GameState):CorporateManagementState {
  if(!state.corporateManagement) state.corporateManagement={version:1,companies:{},loanApplications:[],history:[],lastProcessedTick:-1};
  state.corporateManagement.companies??={}; state.corporateManagement.loanApplications??=[]; state.corporateManagement.history??=[];
  return state.corporateManagement;
}
function company(state:GameState,id:string){return state.companies.find(c=>c.id===id);}
function ownership(c:Company){return c.playerOwnershipPercentage||0;}
function hasRole(c:Company,role:string,npcId?:string){return (c.executives||[]).some(e=>e.role===role && (!npcId||e.npcId===npcId));}
export function corporateControlLevel(state:GameState, companyId:string): CompanyManagementPermission {
  const c=company(state,companyId); if(!c) return 'NONE';
  const isPlayerCeo=hasRole(c,'CEO','player') || c.playerOwnershipPercentage>=51 && hasRole(c,'CEO');
  const isChair=ownership(c)>=51 || (state.corporateSystem?.boardSeats?.[companyId]||[]).some(s=>s.isPlayerSeat);
  if(ownership(c)>=100) return 'OWNER';
  if(isChair) return 'BOARD_CHAIR';
  if(isPlayerCeo) return 'CEO';
  if(ownership(c)>0) return 'SHAREHOLDER';
  return 'NONE';
}
function canManage(state:GameState,id:string){return corporateControlLevel(state,id)!=='NONE' && corporateControlLevel(state,id)!=='SHAREHOLDER';}
function findNpc(state:GameState,npcId:string){return state.livingWorld?.npcs?.find(n=>n.id===npcId);}
function eligibleNpcs(state:GameState, role:string){
  const npcs=state.livingWorld?.npcs||[];
  return npcs.filter(n=>(!n.career?.employerCompanyId || n.career.employerCompanyId==='') && ((role==='CFO'&&((n.skills?.finance||0)>=55)) || (role==='CTO'&&((n.skills?.technical||0)>=55)) || (role==='COO'&&((n.skills?.management||0)>=55)) || (role==='CMO'&&((n.skills?.negotiation||0)>=45)) || (role==='CHRO'&&((n.skills?.management||0)>=50)) || (role==='CAO'&&((n.skills?.management||0)>=45)) || (role==='CPO'&&((n.skills?.technical||0)>=45)) || (role==='General Counsel'&&((n.skills?.politics||0)>=50)) || role==='CEO'));
}

export function initializeCorporateManagementState(state:GameState){ensure(state); state.companies.forEach(c=>ensureCompanyManagement(state,c.id)); return state.corporateManagement!;}
export function ensureCompanyManagement(state:GameState,companyId:string){
  const s=ensure(state); if(!s.companies[companyId]) s.companies[companyId]={departmentBudgets:{OPERATIONS:0,PRODUCTION:0,MARKETING:0,HUMAN_RESOURCES:0,ADMINISTRATION:0,RESEARCH_DEVELOPMENT:0,SALES:0,FINANCE:0},departmentHeadcount:{OPERATIONS:0,PRODUCTION:0,MARKETING:0,HUMAN_RESOURCES:0,ADMINISTRATION:0,RESEARCH_DEVELOPMENT:0,SALES:0,FINANCE:0},organizationStructure:'FUNCTIONAL',productionTarget:1,marketingIntensity:1,hrWagePolicy:1,trainingBudgetMonthly:0,capexBudgetMonthly:0,workingCapitalTargetMonths:2,customerServiceLevel:60,procurementEfficiency:60,managementNotes:[],activeLoanIds:[]}; return s.companies[companyId];
}

export function appointNpcExecutive(state:GameState,companyId:string,npcId:string,role:CorporateDepartmentType|'CEO'|'CFO'|'COO'|'CTO'|'CMO'|'CHRO'|'CAO'|'CPO'|'General Counsel',salary:number){
 const c=company(state,companyId), npc=findNpc(state,npcId); if(!c||!npc) return {success:false,message:'Company or NPC not found.'}; if(!canManage(state,companyId)) return {success:false,message:'You do not have corporate management authority.'};
 if(npc.career?.employerCompanyId && npc.career.employerCompanyId!==companyId) return {success:false,message:'This NPC is already employed elsewhere.'};
 if((c.executives||[]).some(e=>e.role===role)) return {success:false,message:`${role} is already occupied.`};
 const competence=clamp(Math.round(((npc.skills?.management||50)+(npc.skills?.finance||50)+(npc.skills?.technical||50)+(npc.skills?.negotiation||50)+(npc.reputation||50))/5));
 c.executives??=[];
 c.executives.push({id:`exec_${companyId}_${npc.id}_${role}_${state.simulationTick}`,name:`${npc.firstName} ${npc.lastName}`,role:role as any,salaryMonthly:money(salary),competence,loyalty:clamp(55+(npc.reputation||50)*.25),ambition:clamp(50+(npc.influence||50)*.3),personality:'Conservative Prudent',npcId:npc.id} as any);
 npc.career={...(npc.career||{occupation:role,field:c.industry,monthlySalary:salary,employerName:c.name,yearsInRole:0,careerTier:'Executive'}),occupation:role,field:c.industry,monthlySalary:salary,employerName:c.name,employerCompanyId:c.id,careerTier:'Executive'};
 ensure(state).history.unshift({tick:state.simulationTick,companyId,type:'EXECUTIVE_APPOINTMENT',summary:`${npc.firstName} ${npc.lastName} appointed ${role} at ${c.name}.`});
 return {success:true,message:`Appointed ${npc.firstName} ${npc.lastName} as ${role}.`};
}
export function dismissExecutive(state:GameState,companyId:string,execId:string){
 const c=company(state,companyId); if(!c||!canManage(state,companyId)) return {success:false,message:'Management authority required.'}; const e=(c.executives||[]).find(x=>x.id===execId) as any; if(!e) return {success:false,message:'Executive not found.'}; const npc=e.npcId?findNpc(state,e.npcId):undefined; if(npc?.career?.employerCompanyId===c.id) npc.career={...npc.career,employerCompanyId:undefined,employerName:'Unemployed',occupation:'Seeking Employment',careerTier:'Executive'}; const severance=e.salaryMonthly*3; if((c.cashReserve||0)<severance) return {success:false,message:`Insufficient corporate cash for severance of $${severance.toLocaleString()}.`}; c.cashReserve=(c.cashReserve||0)-severance;c.cash=c.cashReserve;c.executives=(c.executives||[]).filter(x=>x.id!==execId);return {success:true,message:`Dismissed ${e.name} with $${severance.toLocaleString()} severance.`};
}
export function hireEmployees(state:GameState,companyId:string,count:number,department:CorporateDepartmentType){
 const c=company(state,companyId),m=ensureCompanyManagement(state,companyId); if(!c||!canManage(state,companyId)) return {success:false,message:'Management authority required.'}; count=Math.floor(count); if(count<=0) return {success:false,message:'Headcount must be positive.'}; const cost=count*c.averageEmployeeSalary; if((c.cashReserve||0)<cost*1.5) return {success:false,message:'Insufficient corporate liquidity for hiring ramp.'}; c.employeesCount+=count;c.cashReserve-=Math.round(cost*.5);c.cash=c.cashReserve;m.departmentHeadcount[department]=(m.departmentHeadcount[department]||0)+count;c.employeeMorale=clamp(c.employeeMorale+Math.min(3,count/500)); return {success:true,message:`Hired ${count.toLocaleString()} employees into ${department.replace(/_/g,' ')}.`};
}
export function restructureCompany(state:GameState,companyId:string,structure:string){const c=company(state,companyId),m=ensureCompanyManagement(state,companyId);if(!c||!canManage(state,companyId))return{success:false,message:'Management authority required.'};m.organizationStructure=structure;m.managementNotes.unshift(`Organization changed to ${structure} at tick ${state.simulationTick}.`);c.employeeProductivity=clamp(c.employeeProductivity+(structure==='DIVISIONAL'?2:structure==='MATRIX'?1:0));c.employeeMorale=clamp(c.employeeMorale-(structure==='MATRIX'?2:0));return{success:true,message:`Organizational structure changed to ${structure}.`};}
export function setCorporateDepartmentBudget(state:GameState,companyId:string,department:CorporateDepartmentType,monthlyBudget:number){const c=company(state,companyId),m=ensureCompanyManagement(state,companyId);if(!c||!canManage(state,companyId))return{success:false,message:'Management authority required.'};if(monthlyBudget<0)return{success:false,message:'Budget cannot be negative.'};m.departmentBudgets[department]=money(monthlyBudget);return{success:true,message:`${department.replace(/_/g,' ')} budget set to $${money(monthlyBudget).toLocaleString()}/month.`};}
export function setCorporateOperatingPolicy(state:GameState,companyId:string,policy:{productionTarget?:number;marketingIntensity?:number;hrWagePolicy?:number;trainingBudgetMonthly?:number;capexBudgetMonthly?:number;customerServiceLevel?:number;procurementEfficiency?:number}){const c=company(state,companyId),m=ensureCompanyManagement(state,companyId);if(!c||!canManage(state,companyId))return{success:false,message:'Management authority required.'};Object.assign(m,policy);c.capacityUtilization=clamp((m.productionTarget||1)*100,20,100)/100;c.marketingBudgetMonthly=money(m.departmentBudgets.MARKETING||c.marketingBudgetMonthly);c.rdBudgetMonthly=money(m.departmentBudgets.RESEARCH_DEVELOPMENT||c.rdBudgetMonthly);return{success:true,message:`Operating policy updated for ${c.name}.`};}
export function applyForCorporateBankLoan(state:GameState,companyId:string,bankId:string,principal:number,termMonths:number){
 const c=company(state,companyId); if(!c||!canManage(state,companyId))return{success:false,message:'Corporate management authority required.'};const bank=EXPANSION2_BANKS.find(b=>b.id===bankId);if(!bank)return{success:false,message:'Bank not found.'};principal=money(principal);if(principal<=0)return{success:false,message:'Loan amount must be positive.'};const leverage=(c.debt||0)/Math.max(1,c.totalAssets||1);const rating=c.creditRating||'BBB';const score={AAA:95,AA:90,A:85,BBB:75,BB:62,B:50,CCC:35}[rating]||65;const coverage=c.monthlyRevenue>0?(c.monthlyNetProfit/Math.max(1,c.monthlyRevenue)) : 0;const approval=clamp(score + coverage*100 - leverage*35 + bank.stability*.15);if(approval<60)return{success:false,message:`${bank.name} declined the facility (underwriting score ${approval.toFixed(0)}/100).`};const base=state.livingWorld?.economy?.benchmarkInterestRate??4.5;const rate=Math.max(3,base+bank.lendingRateMargin+(100-score)/25);const monthlyRate=rate/100/12;const payment=Math.round(principal*(monthlyRate*Math.pow(1+monthlyRate,termMonths))/(Math.pow(1+monthlyRate,termMonths)-1));const app:CorporateLoanApplication={id:`corp_loan_${Date.now()}`,companyId,bankId,bankName:bank.name,principal,interestRateAnnual:Math.round(rate*10)/10,termMonths,monthlyPayment:payment,status:'APPROVED',underwritingScore:approval,createdTick:state.simulationTick,officerNpcId:(state.livingWorld?.npcs||[]).find(n=>n.skills?.finance&&n.career?.employerCompanyId===bank.id)?.id};ensure(state).loanApplications.push(app);ensure(state).companies[companyId].activeLoanIds.push(app.id);c.debt=(c.debt||0)+principal;c.cashReserve=(c.cashReserve||0)+principal;c.cash=c.cashReserve;recordFinancialTransaction(state,{type:'MISCELLANEOUS',category:'INCOME',amount:principal,description:`Corporate loan from ${bank.name} for ${c.name}`,destinationAccount:c.name});return{success:true,message:`${bank.name} approved a $${principal.toLocaleString()} corporate facility at ${rate.toFixed(2)}% APR.` ,application:app};
}
export function simulateMonthlyCorporateManagementV2(state:GameState,news:string[]=[]){const s=ensure(state);if(s.lastProcessedTick===state.simulationTick)return;for(const c of state.companies){const m=ensureCompanyManagement(state,c.id);const budgets=Object.values(m.departmentBudgets).reduce((a,b)=>a+b,0);if(budgets>0&&(c.cashReserve||0)>=budgets){c.cashReserve-=budgets;c.cash=c.cashReserve;c.employeeProductivity=clamp(c.employeeProductivity+Math.min(1.5,budgets/Math.max(1,c.monthlyRevenue)*30));c.employeeMorale=clamp(c.employeeMorale+(m.hrWagePolicy-1)*2);c.productQuality=clamp(c.productQuality+(m.departmentBudgets.RESEARCH_DEVELOPMENT/Math.max(1,c.monthlyRevenue))*20);c.brandReputation=clamp(c.brandReputation+(m.marketingIntensity-1)*.5);}for(const l of s.loanApplications.filter(x=>x.companyId===c.id&&x.status==='APPROVED')){if(c.cashReserve>=l.monthlyPayment){c.cashReserve-=l.monthlyPayment;c.debt=Math.max(0,(c.debt||0)-Math.max(0,l.monthlyPayment-c.debt*(l.interestRateAnnual/100/12)));}else{l.missedPayments=(l.missedPayments||0)+1;c.creditRating='CCC';news.push(`${c.name} missed a corporate loan payment to ${l.bankName}.`);}}}s.lastProcessedTick=state.simulationTick;}
