import { GameState, LifeEvent, PendingDecision } from '../types';
export type DeepPath='CAREER'|'POLITICS'|'BUSINESS'|'TYCOON'|'SPORTS';
type Stats={reputation:number;skill:number;influence:number;capital:number;relationships:number;pressure:number;legacy:number;};
export interface DeepGameplayState{paths:Record<DeepPath,Stats>; history:Array<{tick:number;path:DeepPath;action:string;outcome:string}>}
const paths:DeepPath[]=['CAREER','POLITICS','BUSINESS','TYCOON','SPORTS'];
const base=():Stats=>({reputation:10,skill:10,influence:5,capital:0,relationships:10,pressure:0,legacy:0});
export function ensureDeepGameplay(state:GameState):DeepGameplayState{const s:any=state;if(!s.deepGameplay)s.deepGameplay={paths:Object.fromEntries(paths.map(p=>[p,base()])),history:[]};return s.deepGameplay}
export const DEEP_ACTIONS:Record<DeepPath,Array<{id:string;title:string;tradeoff:string;delta:Partial<Stats>}>>={
 CAREER:[{id:'mentor',title:'Find a mentor',tradeoff:'Costs time but compounds relationships.',delta:{relationships:8,skill:3,pressure:2}},{id:'credential',title:'Earn a credential',tradeoff:'Costs capital and time for long-term access.',delta:{skill:10,capital:-2,pressure:5}},{id:'pivot',title:'Change career lane',tradeoff:'Lose short-term momentum for a new opportunity.',delta:{skill:4,reputation:-2,legacy:4}}],
 POLITICS:[{id:'organize',title:'Organize a local base',tradeoff:'Build trust slowly and visibly.',delta:{relationships:10,influence:7,pressure:3}},{id:'fundraise',title:'Raise campaign funds',tradeoff:'Gain resources while increasing scrutiny.',delta:{capital:8,influence:3,pressure:6}},{id:'negotiate',title:'Negotiate a coalition',tradeoff:'Trade ideological purity for governing power.',delta:{influence:10,relationships:4,reputation:-3}}],
 BUSINESS:[{id:'product',title:'Redesign the product',tradeoff:'Invest now for future demand.',delta:{skill:5,capital:-5,reputation:4,pressure:4}},{id:'expand',title:'Open a new market',tradeoff:'Higher upside and execution risk.',delta:{capital:6,influence:4,pressure:8}},{id:'culture',title:'Rebuild company culture',tradeoff:'Slower growth, stronger retention.',delta:{relationships:9,reputation:5,pressure:2}}],
 TYCOON:[{id:'acquire',title:'Acquire a distressed asset',tradeoff:'Leverage creates scale and financial risk.',delta:{capital:12,influence:6,pressure:9}},{id:'holdco',title:'Create a holding company',tradeoff:'Centralize control and complexity.',delta:{influence:9,legacy:6,pressure:6}},{id:'diversify',title:'Diversify the portfolio',tradeoff:'Reduce concentration at the cost of focus.',delta:{capital:5,reputation:3,pressure:2}}],
 SPORTS:[{id:'academy',title:'Invest in the academy',tradeoff:'Sacrifice short-term wins for future talent.',delta:{skill:8,legacy:5,capital:-4}},{id:'star',title:'Sign a marquee star',tradeoff:'Immediate attention and salary pressure.',delta:{reputation:9,capital:-7,pressure:7}},{id:'rebuild',title:'Commit to a rebuild',tradeoff:'Accept short-term losses to reset the club.',delta:{skill:5,relationships:5,pressure:8,legacy:4}}]};
const clamp=(n:number)=>Math.max(-100,Math.min(100,n));
export function applyDeepAction(state:GameState,path:DeepPath,actionId:string):{ok:boolean;event?:LifeEvent}{const d=ensureDeepGameplay(state);const a=DEEP_ACTIONS[path].find(x=>x.id===actionId);if(!a)return{ok:false};const st=d.paths[path];for(const[k,v]of Object.entries(a.delta))st[k as keyof Stats]=clamp(st[k as keyof Stats]+Number(v));d.history.push({tick:(state as any).simulationTick||0,path,action:actionId,outcome:a.tradeoff});return{ok:true,event:{id:`deep_${path}_${actionId}_${(state as any).simulationTick}`,timestampMonth:state.currentMonth,timestampYear:state.currentYear,age:state.character.age,category:path,type:'DECISION',title:a.title,description:a.tradeoff,severity:'Medium',consequences:{details:[`Your ${path.toLowerCase()} trajectory changed.`]}} as any}}
export function generateDeepDecisions(state:GameState):PendingDecision[]{const d=ensureDeepGameplay(state);const tick=(state as any).simulationTick||0;return paths.filter((_,i)=>(tick+i)%4===0).slice(0,2).map((p,i)=>{const a=DEEP_ACTIONS[p][(tick+i)%DEEP_ACTIONS[p].length];return{id:`deep_${p}_${tick}_${a.id}`,category:p,title:a.title,description:a.tradeoff,options:[{id:a.id,label:'Proceed',description:a.tradeoff},{id:'defer',label:'Defer',description:'Keep current strategy and preserve flexibility.'}],expiresAtTick:tick+2} as any})}
export function advanceDeepGameplay(state:GameState){const d=ensureDeepGameplay(state);const events:LifeEvent[]=[];for(const p of paths){const s=d.paths[p];s.pressure=clamp(s.pressure-1);if(s.skill+s.relationships+s.influence>55){s.legacy=clamp(s.legacy+1);if(s.legacy%10===0)events.push({id:`deep_milestone_${p}_${(state as any).simulationTick}`,timestampMonth:state.currentMonth,timestampYear:state.currentYear,age:state.character.age,category:p,type:'MILESTONE',title:`${p} path reaches a new tier`,description:'Your accumulated choices have unlocked more demanding opportunities.',severity:'High',consequences:{details:['New narrative and strategic opportunities unlocked.']}} as any)}}return{events,decisions:generateDeepDecisions(state)}}
