import { GameState, GovernmentLivingProfile, GovernmentMinistry, GovernmentOfficeLevel } from '../types';

const MINISTRIES: GovernmentMinistry[] = ['Finance','Foreign Affairs','Health','Education','Defence','Infrastructure','Energy','Justice','Commerce','Labour','Environment'];
const GROUPS = ['Workers','Business Owners','Students','Families','Retirees','Low Income Households','Middle Income Households','High Income Households','Rural Communities','Urban Communities'];
const tick=(s:GameState)=>s.simulationTick||((s.currentYear||2026)*12+(s.currentMonth||1));
const npcs=(s:GameState)=>s.livingWorld?.npcs||[];
function npcFor(s:GameState, index:number){return npcs(s)[index % Math.max(1,npcs(s).length)];}
function event(s:GameState,title:string,narrative:string,category:GovernmentLivingProfile['governmentHistory'][number]['category']){
  const g=ensureGovernmentLivingProfile(s); g.governmentHistory.unshift({tick:tick(s),title,narrative,category}); g.governmentHistory=g.governmentHistory.slice(0,150);
  s.eventsFeed?.unshift({id:`gov_${tick(s)}_${Math.random().toString(36).slice(2,7)}`,timestampMonth:s.currentMonth,timestampYear:s.currentYear,age:s.character.age,category:'Politics',title,description:narrative,consequences:{details:[`Government history category: ${category}`]}} as any);
}
export function ensureGovernmentLivingProfile(state:GameState):GovernmentLivingProfile{
  if(state.governmentLiving) return state.governmentLiving;
  const country=state.world[state.currentCountryIndex];
  const civilServants=MINISTRIES.flatMap((m,i)=>{
    const a=npcFor(state,i*2), b=npcFor(state,i*2+1); return [a,b].filter(Boolean).map((n,j)=>({id:`cs_${m}_${j}`,npcId:n.id,name:`${n.firstName} ${n.lastName}`,ministry:m,role:j===0?'Permanent Secretary':'Senior Civil Servant',grade:7-j,competence:Math.round(55+(n.skills?.management||50)*0.35),loyalty:60+(n.reputation%30),integrity:70+(n.reputation%25),salary:9000-j*1500,morale:72,status:'ACTIVE' as const}));
  });
  const ministries=MINISTRIES.map((m,i)=>({id:`ministry_${m.toLowerCase().replace(/ /g,'_')}`,name:m,permanentSecretaryNpcId:civilServants.find(c=>c.ministry===m)?.npcId,budget:Math.max(1,(country?.gdpBillions||1000)*1e6*(i===0?.04:.025)),capacity:70,morale:72,policyPriority:m==='Finance'?'Fiscal stability':m==='Health'?'Public health':'Service delivery',headcount:Math.max(50,civilServants.filter(c=>c.ministry===m).length*100)}));
  const parliamentarians=Array.from({length:24},(_,i)=>{const n=npcFor(state,i+20);const party=state.politics.parties[i%Math.max(1,state.politics.parties.length)];return {id:`mp_${i}`,npcId:n?.id||`npc_${i}`,name:n?`${n.firstName} ${n.lastName}`:`Parliamentarian ${i+1}`,partyId:party?.id||'party_centrist',constituency:country?.cities?.[i%(country.cities?.length||1)]?.name||country?.name||'National',ideology:party?.ideology||'Centrist Coalition',loyalty:50+(i%35),influence:45+(i%45),committee:MINISTRIES[i%MINISTRIES.length],attendance:70+(i%30)};});
  const g:GovernmentLivingProfile={version:1,level:'NATIONAL',ministries,civilServants,parliamentarians,bills:[],budget:{fiscalYear:state.currentYear,totalRevenue:(country?.gdpBillions||1000)*1e6*0.25,totalExpenditure:(country?.gdpBillions||1000)*1e6*0.27,deficit:0,debt:(country?.nationalDebtBillions||100)*1e9,taxRate:country?.incomeTaxRate||28,departmentAllocations:Object.fromEntries(ministries.map(m=>[m.name,m.budget])),publicInvestment:0,welfareSpending:0,defenceSpending:0},projects:[],procurement:[],scandals:[],protestsStrikes:[],demographics:GROUPS.map((group,i)=>({group,approval:country?.publicApprovalOfGov||50,weight:i<4?12:8})),diplomacy:(state.world||[]).filter(c=>c.id!==country?.id).slice(0,8).map(c=>({countryId:c.id,countryName:c.name,relationship:50,tradeAlignment:50,securityAlignment:50,trust:50,activeTreaties:[],disputes:[]})),lobbyingPressure:{},centralBank:{independence:82,policyRate:country?.centralBankInterestRate||4.5,inflationTarget:2,lastDecision:'Inherited baseline policy',policyHistory:[]},election:{nextElectionTick:tick(state)+48,turnout:60,incumbentSupport:country?.publicApprovalOfGov||50,oppositionMomentum:35},governmentHistory:[]};
  g.budget.deficit=g.budget.totalExpenditure-g.budget.totalRevenue; state.governmentLiving=g; return g;
}
function requireOffice(s:GameState, allowed:string[]){const title=s.politics.currentOffice.title;return s.politics.currentOffice.inOffice&&allowed.some(x=>title.includes(x));}
export function appointCivilServant(state:GameState,ministry:GovernmentMinistry,npcId?:string){const g=ensureGovernmentLivingProfile(state);const n=npcId?npcs(state).find(x=>x.id===npcId):npcs(state).find(x=>x.skills?.management&&x.career?.field?.toLowerCase().includes('government'));if(!n)return {success:false,message:'No suitable NPC civil-service candidate found.'};const existing=g.civilServants.find(c=>c.ministry===ministry&&c.status==='ACTIVE'&&c.role==='Permanent Secretary');if(existing){existing.npcId=n.id;existing.name=`${n.firstName} ${n.lastName}`;existing.competence=Math.round(55+(n.skills?.management||50)*.35);}else g.civilServants.push({id:`cs_${tick(state)}_${n.id}`,npcId:n.id,name:`${n.firstName} ${n.lastName}`,ministry,role:'Senior Civil Servant',grade:7,competence:Math.round(55+(n.skills?.management||50)*.35),loyalty:60,integrity:70,salary:8500,morale:70,status:'ACTIVE'});event(state,`Civil Service Appointment: ${ministry}`,`${n.firstName} ${n.lastName} joins the ${ministry} administration as a senior civil servant. The appointment affects departmental capacity and internal politics.`,'POLICY');return {success:true,message:`Appointed ${n.firstName} ${n.lastName} to ${ministry}.`};}
export function passGovernmentBill(state:GameState,title:string,area:string,cost:number){if(!requireOffice(state,['Mayor','Minister','President','Prime','Parliament']))return {success:false,message:'You lack the public mandate to sponsor this bill.'};const g=ensureGovernmentLivingProfile(state);const sponsor=state.character.id;const party=state.politics.selectedPartyId||'party_centrist';const support=g.parliamentarians.filter(m=>m.partyId===party).length*2+state.politics.currentOffice.politicalCapital*.2;const against=Math.max(0,100-support);const bill={id:`bill_${tick(state)}_${Date.now()}`,title,sponsorNpcId:sponsor,sponsorName:`${state.character.firstName} ${state.character.lastName}`,chamber:'PARLIAMENT' as const,status:'PASSED' as const,supportFor:Math.min(100,support),supportAgainst:against,fiscalCost:cost,policyArea:area};g.bills.unshift(bill);g.budget.totalExpenditure+=cost;g.budget.deficit=g.budget.totalExpenditure-g.budget.totalRevenue;g.demographics.forEach(d=>d.approval=Math.max(0,Math.min(100,d.approval+(area==='HEALTH'?2:0))));event(state,`Parliament Passes: ${title}`,`The government secures legislative approval for ${title}. The measure carries an estimated fiscal cost of $${cost.toLocaleString()}.`,'POLICY');return {success:true,message:`Bill passed with estimated support ${Math.round(support)}%.`};}
export function allocateGovernmentBudget(state:GameState,ministry:GovernmentMinistry,amount:number){if(!requireOffice(state,['Mayor','Minister','President','Prime']))return {success:false,message:'Budget authority is not available to your current office.'};const g=ensureGovernmentLivingProfile(state);g.budget.departmentAllocations[ministry]=Math.max(0,amount);const m=g.ministries.find(x=>x.name===ministry);if(m){m.budget=amount;m.capacity=Math.max(0,Math.min(100,m.capacity+(amount/Math.max(1,m.budget)-1)*10));}event(state,`Budget Allocation: ${ministry}`,`The administration changes the ${ministry} budget to $${amount.toLocaleString()}. Departmental capacity and service delivery will adjust over subsequent months.`,'POLICY');return {success:true,message:`${ministry} budget updated.`};}
export function launchPublicProject(state,name:string,category:GovernmentLivingProfile['projects'][number]['category'],budget:number){if(!requireOffice(state,['Mayor','Minister','President','Prime']))return {success:false,message:'You do not control this public investment level.'};const g=ensureGovernmentLivingProfile(state);if(g.budget.deficit+budget>g.budget.totalRevenue*.5 && state.politics.currentOffice.title.includes('President'))return {success:false,message:'Fiscal constraints prevent this project without additional financing.'};g.projects.push({id:`proj_${tick(state)}_${Date.now()}`,name,category,jurisdiction:state.politics.currentOffice.cityOrNation,budget,spent:0,progress:0,jobsCreated:Math.max(5,Math.round(budget/50000)),status:'PLANNED'});g.budget.publicInvestment+=budget;g.budget.totalExpenditure+=budget;g.budget.deficit=g.budget.totalExpenditure-g.budget.totalRevenue;event(state,`Public Project Approved: ${name}`,`A ${category.toLowerCase()} project is approved in ${state.politics.currentOffice.cityOrNation}, creating approximately ${Math.max(5,Math.round(budget/50000))} jobs over its construction cycle.`,'PROCUREMENT');return {success:true,message:`Public project approved: ${name}.`};}
export function awardProcurement(state,title:string,ministry:GovernmentMinistry,supplierName:string,value:number){if(!requireOffice(state,['Mayor','Minister','President','Prime']))return {success:false,message:'You lack procurement authority.'};const g=ensureGovernmentLivingProfile(state);const c=state.companies.find(c=>c.name===supplierName||c.id===supplierName);g.procurement.push({id:`contract_${tick(state)}_${Date.now()}`,title,ministry,companyId:c?.id,supplierName:c?.name||supplierName,value,durationMonths:12,status:'AWARDED',integrityRisk:10+Math.random()*35});g.budget.totalExpenditure+=value/12;g.budget.deficit=g.budget.totalExpenditure-g.budget.totalRevenue;event(state,`Government Contract Awarded: ${title}`,`The ${ministry} ministry awards a $${value.toLocaleString()} public contract to ${c?.name||supplierName}. Procurement oversight remains active.`,'PROCUREMENT');return {success:true,message:`Contract awarded to ${c?.name||supplierName}.`};}
export function setTaxRate(state,rate:number){if(!requireOffice(state,['President','Prime','Minister']))return {success:false,message:'National taxation authority is unavailable.'};const g=ensureGovernmentLivingProfile(state);const oldRate=g.budget.taxRate;g.budget.taxRate=Math.max(0,Math.min(60,rate));const country=state.world[state.currentCountryIndex];if(country)country.incomeTaxRate=g.budget.taxRate;g.budget.totalRevenue=Math.max(0,g.budget.totalRevenue*(1+(g.budget.taxRate-oldRate)/100*0.65));g.demographics.forEach(d=>d.approval=Math.max(0,Math.min(100,d.approval+(rate<30?1:-1))));event(state,'Tax Policy Changed',`National income taxation is adjusted to ${rate}%. Household finances, consumption, investment and public revenue will respond through the wider simulation.`,'ECONOMY');return {success:true,message:`Income tax set to ${rate}%.`};}
export function setCentralBankRate(state,rate:number){const g=ensureGovernmentLivingProfile(state);if(g.centralBank.independence>50 && !state.politics.currentOffice.title.includes('Central'))return {success:false,message:'The central bank is operationally independent; political leadership cannot directly set its policy rate.'};g.centralBank.policyRate=Math.max(0,Math.min(20,rate));g.centralBank.lastDecision=`Policy rate set to ${rate}%`;g.centralBank.policyHistory.unshift({tick:tick(state),rate,reason:'Monetary policy decision'});const country=state.world[state.currentCountryIndex];if(country)country.centralBankInterestRate=rate;event(state,'Central Bank Rate Decision',`The monetary authority changes the policy rate to ${rate}%, affecting borrowing costs, savings yields, inflation pressure and investment conditions.`,'ECONOMY');return {success:true,message:`Policy rate set to ${rate}%.`};}
export function conductDiplomacy(state:GameState,countryId:string,action:'SUMMIT'|'TRADE_DEAL'|'TREATY'|'SANCTIONS'){if(!requireOffice(state,['President','Prime','Foreign']))return {success:false,message:'Only appropriate national diplomatic authority can conduct this action.'};const g=ensureGovernmentLivingProfile(state);const d=g.diplomacy.find(x=>x.countryId===countryId);if(!d)return {success:false,message:'Diplomatic partner not found.'};const delta=action==='SANCTIONS'?-12:action==='TREATY'?10:action==='TRADE_DEAL'?7:4;d.relationship=Math.max(-100,Math.min(100,d.relationship+delta));if(action==='TREATY')d.activeTreaties.push(`Treaty ${tick(state)}`);if(action==='SANCTIONS')d.disputes.push(`Sanctions ${tick(state)}`);event(state,`Diplomatic Action: ${action}`,`The government conducts ${action.toLowerCase().replace('_',' ')} with ${d.countryName}. Bilateral relations now stand at ${d.relationship}.`,'DIPLOMACY');return {success:true,message:`Diplomatic action completed with ${d.countryName}.`};}
export function simulateMonthlyGovernmentLiving(state:GameState){const g=ensureGovernmentLivingProfile(state);const country=state.world[state.currentCountryIndex];const macro=state.livingWorld?.economy;g.budget.totalRevenue=Math.max(0,g.budget.totalRevenue*(1+(macro?.nationalGdpGrowth||country?.gdpGrowthRate||2)/120));g.budget.totalExpenditure=Math.max(0,g.budget.totalExpenditure);g.budget.deficit=g.budget.totalExpenditure-g.budget.totalRevenue;g.budget.debt+=Math.max(0,g.budget.deficit);g.ministries.forEach(m=>{const staff=g.civilServants.filter(c=>c.ministry===m.name&&c.status==='ACTIVE');m.morale=Math.max(0,Math.min(100,m.morale+(staff.reduce((a,c)=>a+c.morale,0)/Math.max(1,staff.length)-m.morale)*.05));m.capacity=Math.max(0,Math.min(100,m.capacity+(m.morale-50)*.01));});g.projects.forEach(p=>{if(p.status==='PLANNED')p.status='ACTIVE';if(p.status==='ACTIVE'){p.spent+=p.budget/Math.max(3,12);p.progress=Math.min(100,p.progress+100/Math.max(3,12));if(p.progress>=100)p.status='COMPLETED';}});g.procurement.forEach(c=>{if(c.status==='AWARDED')c.status='ACTIVE';});g.demographics.forEach(d=>{const taxPressure=(g.budget.taxRate-(country?.incomeTaxRate||g.budget.taxRate))*.05;d.approval=Math.max(0,Math.min(100,d.approval+(country?.publicApprovalOfGov||50-d.approval)*.04-taxPressure));});
  if(Math.random()<.035){const ministry=MINISTRIES[Math.floor(Math.random()*MINISTRIES.length)];g.scandals.unshift({id:`scandal_${tick(state)}`,title:`${ministry} procurement inquiry`,severity:Math.random()<.7?'MINOR':'MAJOR',involvedNpcIds:g.civilServants.filter(c=>c.ministry===ministry).slice(0,2).map(c=>c.npcId),ministry,approvalImpact:-3,resolved:false});event(state,`Scandal: ${ministry} Inquiry`,`Investigators open an inquiry into the ${ministry} ministry. The government faces questions over administrative integrity and oversight.`,'SCANDAL');}
  if(Math.random()<.025){const type=Math.random()<.5?'PROTEST':'STRIKE';g.protestsStrikes.unshift({id:`social_${tick(state)}`,type,title:type==='PROTEST'?'Public demonstration over living costs':'National labour strike',group:type==='PROTEST'?'Urban Communities':'Workers',intensity:35+Math.random()*50,participants:500+Math.round(Math.random()*20000),approvalImpact:-4,active:true});event(state,`${type}: Public Pressure Rises`,type==='PROTEST'?'Large groups demonstrate over government policy and household costs.':'Workers coordinate industrial action over wages and employment conditions.','PROTEST');}
  if(tick(state)>=g.election.nextElectionTick){g.election.nextElectionTick=tick(state)+48;g.election.turnout=Math.max(35,Math.min(90,55+Math.random()*20));event(state,'Election Cycle Opens','The constitutional election cycle opens. Parties begin candidate selection, fundraising, debates and voter mobilization.','ELECTION');}
  if(Math.random()<.03){const d=g.diplomacy[Math.floor(Math.random()*Math.max(1,g.diplomacy.length))];if(d){d.relationship=Math.max(-100,Math.min(100,d.relationship+(Math.random()*8-4)));}}
  if(country){country.publicApprovalOfGov=Math.round(g.demographics.reduce((a,d)=>a+d.approval*d.weight,0)/Math.max(1,g.demographics.reduce((a,d)=>a+d.weight,0)));}
}
