import { GameState } from '../types';
import { recordWorldPlayerAction } from './worldGovernorCoordinator';
export type JusticeAgencyType='LAW_FIRM'|'HOSPITAL'|'ACCOUNTING_FIRM'|'LAW_ENFORCEMENT'|'COURT';
export interface JusticeWorldState { agencies:{id:string;name:string;type:JusticeAgencyType;city:string;reputation:number;capacity:number}[]; playerStatus:'FREE'|'UNDER_INVESTIGATION'|'ARRESTED'|'INCARCERATED'|'ON_BAIL'; charges:{id:string;title:string;severity:'MISDEMEANOR'|'FELONY';status:'OPEN'|'DISMISSED'|'CONVICTED'|'ACQUITTED';sentenceMonths:number;fine:number}[]; prison:{facility:string;gangId?:string;lettersSent:number;progression:number}; history:{tick:number;summary:string}[]; }
const names={LAW_FIRM:['Northstar Legal Group','Crownline Advocates'],HOSPITAL:['Harbour Medical Centre','Grand Meridian Hospital'],ACCOUNTING_FIRM:['LedgerPoint Advisory','Sterling Accounts'],LAW_ENFORCEMENT:['National Police Service','Metropolitan Investigations Bureau'],COURT:['High Court of Meridian','Central District Court']};
export function ensureJusticeWorld(state:GameState):JusticeWorldState{if(state.justiceWorld)return state.justiceWorld as any;const agencies=Object.entries(names).flatMap(([type,list])=>list.map((name,i)=>({id:`agency_${type}_${i}`,name,type:type as JusticeAgencyType,city:state.character.residenceCity,reputation:70+i*8,capacity:75})));const j:JusticeWorldState={agencies,playerStatus:'FREE',charges:[],prison:{facility:'Central Correctional Facility',lettersSent:0,progression:0},history:[]};state.justiceWorld=j as any;return j;}
export function seekLegalCounsel(state:GameState){const j=ensureJusticeWorld(state);state.character.reputation=Math.min(100,(state.character.reputation||0)+2);j.history.unshift({tick:state.simulationTick,summary:'Player retained legal counsel.'});recordWorldPlayerAction(state,'LEGAL_COUNSEL','Retained legal counsel.',['justice','wealth'],55); return {success:true,message:'Legal counsel retained. Your legal affairs are now represented.'};}
export function visitHospital(state:GameState){ensureJusticeWorld(state);state.character.attributes.health=Math.min(100,state.character.attributes.health+10);state.finances.cash=Math.max(0,state.finances.cash-500);return {success:true,message:'Medical consultation completed. Health improved and $500 was charged.'};}
export function commitMinorOffense(state:GameState){const j=ensureJusticeWorld(state);if(j.playerStatus!=='FREE')return {success:false,message:'You cannot attempt this while already under justice supervision.'};const caught=Math.random()<0.28+(state.character.reputation<30?0.12:0);if(caught){j.playerStatus='UNDER_INVESTIGATION';j.charges.push({id:`charge_${Date.now()}`,title:'Public-order offense',severity:'MISDEMEANOR',status:'OPEN',sentenceMonths:2,fine:1500});j.history.unshift({tick:state.simulationTick,summary:'Player was placed under investigation after a minor offense.'}); recordWorldPlayerAction(state,'LEGAL_RISK','Player came under investigation after a minor offense.',['justice','career','family'],85);return {success:true,message:'You committed a minor offense and have come under investigation. The justice system may now respond.'};}state.character.reputation=Math.max(0,(state.character.reputation||0)-3);return {success:true,message:'You got away with a minor offense, but your reputation has taken a hidden risk.'};}
export function sendPrisonLetter(state:GameState){const j=ensureJusticeWorld(state);if(j.playerStatus!=='INCARCERATED')return {success:false,message:'You are not incarcerated.'};j.prison.lettersSent+=1;return {success:true,message:'Letter sent to your family from prison.'};}
export function joinPrisonGang(state:GameState){const j=ensureJusticeWorld(state);if(j.playerStatus!=='INCARCERATED')return {success:false,message:'This action is only available in prison.'};j.prison.gangId=j.prison.gangId||`gang_${Date.now()}`;j.prison.progression=Math.min(100,j.prison.progression+8);return {success:true,message:'You joined a prison gang. Loyalty and risk now affect your prison experience.'};}
export function simulateMonthlyJusticeStep(state:GameState){const j=ensureJusticeWorld(state);if(j.playerStatus==='UNDER_INVESTIGATION'){const charge=j.charges.find(c=>c.status==='OPEN');if(charge&&Math.random()<0.35){j.playerStatus='ARRESTED';}}else if(j.playerStatus==='ARRESTED'){j.playerStatus='INCARCERATED';state.character.reputation=Math.max(0,state.character.reputation-12);state.currentJob=null;state.character.occupation='Incarcerated';}else if(j.playerStatus==='INCARCERATED'){j.prison.progression=Math.min(100,j.prison.progression+2);const c=j.charges.find(c=>c.status==='OPEN');if(c){c.sentenceMonths-=1;if(c.sentenceMonths<=0){c.status='CONVICTED';j.playerStatus='FREE';state.character.occupation='Released / Seeking Work';state.character.reputation=Math.max(0,state.character.reputation-8);}}}}
