import { GameState, LivingWealthState, InvestmentPlatform, LivingBankOfficer, LivingInvestmentAdvisor } from '../types';
import { EXPANSION2_BANKS } from '../data/expansion2Catalogs';
import { ensureCreditProfileState } from './creditEngine';
import { recordFinancialTransaction } from './financialLedgerEngine';
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
export function ensureLivingWealthState(state:GameState):LivingWealthState{if(!state.livingWealth) state.livingWealth={version:1,investmentPlatforms:[],bankOfficers:[],investmentAdvisors:[],corporateBankRelationships:{},investmentResearch:{},wealthHistory:[]};const s=state.livingWealth;s.investmentPlatforms??=[];s.bankOfficers??=[];s.investmentAdvisors??=[];s.corporateBankRelationships??={};s.investmentResearch??={};s.wealthHistory??=[];if(!s.investmentPlatforms.length)s.investmentPlatforms=EXPANSION2_BANKS.map((b,i)=>({id:`platform_${b.id}`,name:`${b.name} Wealth & Markets`,bankId:b.id,platformType:b.category==='INVESTMENT_BANK'?'EXCHANGE':b.category==='PRIVATE_BANK'?'PRIVATE_WEALTH':'BROKERAGE',feeRate:b.category==='PRIVATE_BANK'?0.75:0.35,reputation:b.reputation,assetsUnderManagement:1000000000+i*75000000,clientCount:50000+i*3500}));return s;}
function npcs(state:GameState){return state.livingWorld?.npcs||[];}
export function refreshLivingWealthPeople(state:GameState){const s=ensureLivingWealthState(state);for(const b of EXPANSION2_BANKS){if(!s.bankOfficers.some(x=>x.bankId===b.id)){const npc=npcs(state).find(n=>((n.skills?.finance||0)>=55)&&(!n.career?.employerCompanyId||n.career.employerCompanyId===b.id));if(npc)s.bankOfficers.push({npcId:npc.id,bankId:b.id,title:'Relationship & Credit Officer',relationshipScore:50,underwritingInfluence:clamp((npc.skills?.finance||50)*.7)});}}for(const p of s.investmentPlatforms){if(!s.investmentAdvisors.some(x=>x.platformId===p.id)){const npc=npcs(state).find(n=>(n.skills?.finance||0)>=60);if(npc)s.investmentAdvisors.push({npcId:npc.id,platformId:p.id,specialization:'EQUITIES',relationshipScore:50});}}
}
export function openCorporateBankRelationship(state:GameState,companyId:string,bankId:string){const s=ensureLivingWealthState(state);const bank=EXPANSION2_BANKS.find(b=>b.id===bankId);const c=state.companies.find(x=>x.id===companyId);if(!bank||!c)return{success:false,message:'Company or bank not found.'};refreshLivingWealthPeople(state);const officer=s.bankOfficers.find(x=>x.bankId===bankId);const base=bank.stability*50000;const credit=(c.creditRating||'BBB');const mult=credit==='AAA'?3:credit==='AA'?2.5:credit==='A'?2:credit==='BBB'?1.5:.8;const limit=Math.round(base*mult);const arr=s.corporateBankRelationships[companyId]||[];if(!arr.some(x=>x.bankId===bankId))arr.push({bankId,relationshipScore:officer?.relationshipScore||50,creditLimit:limit,lastDecisionTick:state.simulationTick});s.corporateBankRelationships[companyId]=arr;return{success:true,message:`${bank.name} relationship established with a preliminary corporate credit capacity of $${limit.toLocaleString()}.`};}
export function requestInvestmentResearch(state:GameState,symbol:string){const s=ensureLivingWealthState(state);const asset=state.investmentMarket?.marketAssets.find(a=>a.symbol===symbol)||state.investmentMarket?.marketAssets.find(a=>a.id===symbol);if(!asset)return{success:false,message:'Asset not found.'};refreshLivingWealthPeople(state);const advisor=s.investmentAdvisors.find(a=>a.specialization==='EQUITIES');const company=asset.underlyingCompanyId?state.companies.find(c=>c.id===asset.underlyingCompanyId):undefined;const earnings=company?.monthlyNetProfit||0;const rating=earnings>0?'BUY':'SELL';const thesis=company?`${company.name}: revenue $${company.monthlyRevenue.toLocaleString()}/mo, profit $${earnings.toLocaleString()}/mo, employee productivity ${company.employeeProductivity}%.`:`Market asset ${asset.name} lacks a corporate operating profile.`;s.investmentResearch[asset.symbol]={rating,confidence:clamp(55+(company?company.employeeProductivity-50:0)),thesis,analystNpcId:advisor?.npcId};return{success:true,message:`Research issued: ${rating}.`,research:s.investmentResearch[asset.symbol]};}
export function transferCashToInvestmentPlatform(state:GameState,platformId:string,amount:number){const s=ensureLivingWealthState(state);const p=s.investmentPlatforms.find(x=>x.id===platformId);if(!p)return{success:false,message:'Investment platform not found.'};if(amount<=0||state.finances.cash<amount)return{success:false,message:'Insufficient cash.'};state.finances.cash-=amount;p.assetsUnderManagement+=amount;recordFinancialTransaction(state,{type:'MISCELLANEOUS',category:'TRANSFER',amount,description:`Transferred cash to ${p.name}`,sourceAccount:'Liquid Cash',destinationAccount:p.name});return{success:true,message:`Transferred $${amount.toLocaleString()} to ${p.name}.`};}
export function simulateMonthlyLivingWealth(state:GameState){const s=ensureLivingWealthState(state);refreshLivingWealthPeople(state);const econ=state.livingWorld?.economy;for(const b of EXPANSION2_BANKS){b.totalDeposits??=5000000000+b.stability*25000000;b.totalLoans??=b.totalDeposits*.72;b.netInterestMargin??=Math.max(1,b.lendingRateMargin-b.depositRateBonus);b.capitalRatio??=10+b.stability/20;b.nonPerformingLoanRate??=Math.max(1,(100-b.stability)/15);b.marketShare??=5+b.reputation/20;b.activeCorporateClients??=1000+b.reputation*20;const creditShock=econ?.creditAvailability==='Tight'?-0.02:econ?.creditAvailability==='Loose'?0.02:econ?.creditAvailability==='Frozen'?-0.08:0;const g=(econ?.nationalGdpGrowth||0)/100/12;b.totalDeposits=Math.max(0,b.totalDeposits*(1+g+creditShock));b.totalLoans=Math.max(0,b.totalLoans*(1+g*.8+creditShock*.5));b.nonPerformingLoanRate=clamp(b.nonPerformingLoanRate+(econ?.currentCycle==='Recession'?0.12:-0.04));b.monthlyProfit=Math.round((b.totalLoans*b.netInterestMargin/100/12)-(b.totalDeposits*.001/12));}for(const p of s.investmentPlatforms){const market=(econ?.marketConfidenceIndex||50)-50;p.assetsUnderManagement=Math.max(0,p.assetsUnderManagement*(1+(econ?.nationalGdpGrowth||0)/100/12+market/10000));}for(const arr of Object.values(s.corporateBankRelationships))for(const r of arr)r.relationshipScore=clamp(r.relationshipScore+(state.simulationTick%4===0?1:0));ensureCreditProfileState(state);}
