import { GameState } from '../types';
import { ensureRealEstatePlatform } from './realEstatePlatformEngine';

type RE = NonNullable<GameState['realEstateIndustry']>;
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const rng=(state:GameState, salt:string)=>{let s=2166136261;const x=`${state.character.id}|${state.simulationTick}|${salt}`;for(const c of x){s^=c.charCodeAt(0);s=Math.imul(s,16777619);}return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};};

export function ensureRealEstateIndustry(state:GameState):RE{
 if(!state.realEstateIndustry) state.realEstateIndustry={version:2,agents:[],propertyManagers:[],tenants:[],mortgages:[],contractors:[],professionals:[],permits:[],inspections:[],auctions:[],distressedAssets:[],taxes:[],insurancePolicies:[],commercialLeases:[],reits:[],jvs:[],spvs:[],developmentFinancing:[],preSales:[],constructionContracts:[],companyEmployees:[],industryHistory:[],lastProcessedTick:-1};
 const r=state.realEstateIndustry; for(const k of ['agents','propertyManagers','tenants','mortgages','contractors','professionals','permits','inspections','auctions','distressedAssets','taxes','insurancePolicies','commercialLeases','reits','jvs','spvs','developmentFinancing','preSales','constructionContracts','companyEmployees','industryHistory'] as const) (r[k] as any)??=[]; return r;
}

function pushHistory(state:GameState, title:string, narrative:string, significance:'INFO'|'MAJOR'|'CRISIS'='INFO'){
 const r=ensureRealEstateIndustry(state); r.industryHistory.unshift({tick:state.simulationTick,month:state.currentMonth,year:state.currentYear,title,narrative,significance}); r.industryHistory=r.industryHistory.slice(0,100);
}

export function seedRealEstateIndustry(state:GameState){
 const r=ensureRealEstateIndustry(state); if(r.agents.length||r.contractors.length) return r;
 const cities=[['Cape Town','South Africa'],['Johannesburg','South Africa'],['London','United Kingdom'],['New York','United States'],['Dubai','United Arab Emirates']];
 cities.forEach(([city,country],i)=>{r.agents.push({id:`agent_${i}`,name:['Amina Naidoo','Daniel Mokoena','Sarah Bennett','Marcus Reed','Layla Haddad'][i],agency:`${city} Property Partners`,city,country,reputation:70+i*4,dealVolume:0,commissionRate:2.5});r.propertyManagers.push({id:`pm_${i}`,name:['Thabo Ndlovu','Emily Carter','Noah Williams','Sofia Grant','Omar Rahman'][i],company:`${city} Asset Management`,city,country,reputation:72+i*3,managedUnits:0,occupancyRate:94});r.contractors.push({id:`builder_${i}`,name:['Cape BuildWorks','UrbanCore Construction','Crown Developments','MetroBuild Group','Gulf Projects Co.'][i],city,country,reputation:68+i*5,capacity:50+i*10,quality:72+i*4,backlog:0});r.professionals.push({id:`prof_${i}`,name:`${city} Planning & Design`,discipline:i%2?'Architecture':'Engineering',reputation:75+i*3,capacity:20+i*4});});
 ['Family Tenant','Professional Couple','Young Executive','Retail Operator','Logistics Company','Hotel Operator','Office Tenant'].forEach((n,i)=>r.tenants.push({id:`tenant_${i}`,name:n,type:i<3?'RESIDENTIAL':'COMMERCIAL',creditQuality:70+i*3,income:35000+i*25000,reliability:80+i*2,activeLeaseId:null}));
 r.reits.push({id:'reit_1',name:'Global Property Income REIT',strategy:'Income',aum:750000000,occupancy:91,leverage:38,dividendYield:6.4});
 r.reits.push({id:'reit_2',name:'Urban Growth REIT',strategy:'Growth',aum:420000000,occupancy:88,leverage:44,dividendYield:3.8});
 pushHistory(state,'Real Estate Industry 2.0 initialized','Agents, managers, tenants, lenders, contractors, professional services and institutional property investors enter the living property market.'); return r;
}

export function createMortgage(state:GameState, propertyId:string, principal:number, rate:number, termMonths:number, lender='Dominium Bank'){
 const r=ensureRealEstateIndustry(state); const m={id:`mort_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,propertyId,principal,remainingBalance:principal,interestRateAnnual:rate,termMonthsRemaining:termMonths,monthlyPayment:Math.round(principal*(rate/100/12)/(1-Math.pow(1+rate/100/12,-termMonths))),lender,status:'ACTIVE' as const}; r.mortgages.push(m); return m;
}

export function createCommercialLease(state:GameState, propertyId:string, tenantId:string, monthlyRent:number, termMonths:number){const r=ensureRealEstateIndustry(state);const l={id:`lease_${Date.now()}`,propertyId,tenantId,monthlyRent,termMonthsRemaining:termMonths,escalationAnnual:3,status:'ACTIVE' as const};r.commercialLeases.push(l);const t=r.tenants.find(x=>x.id===tenantId);if(t)t.activeLeaseId=l.id;return l;}
export function createPermit(state:GameState, projectId:string, type:string, authority:string){const r=ensureRealEstateIndustry(state);const p={id:`permit_${Date.now()}`,projectId,type,authority,status:'SUBMITTED' as const,monthsPending:0};r.permits.push(p);return p;}
export function scheduleInspection(state:GameState, projectId:string, type:string){const r=ensureRealEstateIndustry(state);const i={id:`inspection_${Date.now()}`,projectId,type,status:'SCHEDULED' as const,score:0};r.inspections.push(i);return i;}
export function createConstructionContract(state:GameState, projectId:string, contractorId:string, value:number){const r=ensureRealEstateIndustry(state);const c=r.contractors.find(x=>x.id===contractorId);if(!c)return null;const x={id:`contract_${Date.now()}`,projectId,contractorId,value,progress:0,status:'ACTIVE' as const,variationReserve:value*.08};r.constructionContracts.push(x);c.backlog+=value;return x;}
export function createJV(state:GameState, projectId:string, partnerName:string, equity:number, sharePercent:number){const r=ensureRealEstateIndustry(state);const j={id:`jv_${Date.now()}`,projectId,partnerName,equity,sharePercent,status:'ACTIVE' as const};r.jvs.push(j);return j;}
export function createSPV(state:GameState, projectId:string, name:string){const r=ensureRealEstateIndustry(state);const s={id:`spv_${Date.now()}`,projectId,name,entityStatus:'ACTIVE' as const,bankAccountBalance:0,debt:0};r.spvs.push(s);return s;}
export function createDevelopmentFinance(state:GameState, projectId:string, lender:string, amount:number, rate:number){const r=ensureRealEstateIndustry(state);const f={id:`devfin_${Date.now()}`,projectId,lender,amount,drawn:0,interestRateAnnual:rate,status:'COMMITTED' as const};r.developmentFinancing.push(f);return f;}
export function createPreSale(state:GameState, projectId:string, buyerName:string, value:number){const r=ensureRealEstateIndustry(state);const p={id:`presale_${Date.now()}`,projectId,buyerName,value,status:'RESERVED' as const};r.preSales.push(p);return p;}
export function createREIT(state:GameState,name:string,strategy:'Income'|'Growth'|'Mixed',aum:number){const r=ensureRealEstateIndustry(state);const x={id:`reit_${Date.now()}`,name,strategy,aum,occupancy:90,leverage:35,dividendYield:5};r.reits.push(x);return x;}
export function startAuction(state:GameState,assetId:string,reserve:number,type:'VOLUNTARY'|'DISTRESSED'='VOLUNTARY'){const r=ensureRealEstateIndustry(state);const a={id:`auction_${Date.now()}`,assetId,reservePrice:reserve,currentBid:0,bidderCount:0,type,status:'OPEN' as const,monthsOpen:0};r.auctions.push(a);return a;}
export function createPropertyTax(state:GameState,propertyId:string,annualAmount:number){const r=ensureRealEstateIndustry(state);const t={id:`tax_${Date.now()}`,propertyId,annualAmount,status:'CURRENT' as const};r.taxes.push(t);return t;}
export function createInsurancePolicy(state:GameState,propertyId:string,provider:string,annualPremium:number,coverageAmount:number){const r=ensureRealEstateIndustry(state);const x={id:`ins_${Date.now()}`,propertyId,provider,annualPremium,coverageAmount,status:'ACTIVE' as const};r.insurancePolicies.push(x);return x;}
export function registerDistressedAsset(state:GameState,assetId:string,reason:string,discountPercent:number){const r=ensureRealEstateIndustry(state);const x={id:`dist_${Date.now()}`,assetId,reason,discountPercent,status:'WATCH' as const};r.distressedAssets.push(x);return x;}
export function sellLandParcel(state:GameState,parcelId:string,price:number){const r=ensureRealEstatePlatform(state);const land=r.landParcels.find(x=>x.id===parcelId&&x.status!=='SOLD');if(!land)return {success:false,message:'Land parcel not found.'};state.finances.cash+=price;land.status='SOLD';land.currentValue=price;r.transactions.unshift({id:`re_tx_${Date.now()}`,month:state.currentMonth,year:state.currentYear,type:'LAND_SALE',assetName:land.name,amount:price,counterparty:'Market Buyer',description:`Sold land parcel ${land.name}.`});return {success:true,message:`Sold ${land.name} for $${price.toLocaleString()}.`};}

export function simulateMonthlyRealEstateIndustry(state:GameState, news:string[]=[]){
 const r=seedRealEstateIndustry(state); if(r.lastProcessedTick===state.simulationTick)return; const random=rng(state,'re'); const platform=ensureRealEstatePlatform(state); const macro=state.livingWorld?.economy; const pressure=((macro?.nationalGdpGrowth||2)-2)/100; const vacancy=platform.averageVacancyRate;
 for(const pm of r.propertyManagers) pm.occupancyRate=clamp(pm.occupancyRate+(95-vacancy-pm.occupancyRate)*.04);
 for(const t of r.tenants) t.reliability=clamp(t.reliability+(random()-.5)*2+(macro?.currentCycle==='Recession'?-1:0));
 for(const m of r.mortgages){if(m.status!=='ACTIVE')continue;m.termMonthsRemaining=Math.max(0,m.termMonthsRemaining-1);const interest=m.remainingBalance*m.interestRateAnnual/100/12;m.remainingBalance=Math.max(0,m.remainingBalance-m.monthlyPayment+interest);if(m.termMonthsRemaining===0||m.remainingBalance<1)m.status='PAID_OFF';}
 for(const l of r.commercialLeases){if(l.status!=='ACTIVE')continue;l.termMonthsRemaining--;if(l.termMonthsRemaining<=0){l.status='EXPIRED';news.push(`A commercial lease expired, opening a new tenant opportunity in the property market.`);}else if(state.simulationTick%12===0)l.monthlyRent*=1+l.escalationAnnual/100;}
 for(const p of r.permits){if(p.status!=='SUBMITTED')continue;p.monthsPending++;const project=platform.projects.find(x=>x.id===p.projectId);if(p.monthsPending>1&&random()<.35){p.status='APPROVED';if(project)project.approvalRisk=clamp(project.approvalRisk-8);news.push(`Municipal authorities approved a ${p.type.toLowerCase()} permit for ${project?.name||'a development project'}.`);}else if(p.monthsPending>4&&random()<.18){p.status='REJECTED';if(project){project.status='DELAYED';project.approvalRisk=clamp(project.approvalRisk+12);}news.push(`Planning approval was rejected for ${project?.name||'a development project'}, delaying the scheme.`);}}
 for(const i of r.inspections){if(i.status!=='SCHEDULED')continue;if(random()<.75){i.status=random()<.12?'FAILED':'PASSED';i.score=Math.round(65+random()*30);const project=platform.projects.find(x=>x.id===i.projectId);if(project&&i.status==='FAILED'){project.constructionQuality=clamp(project.constructionQuality-10);project.costOverrunRisk=clamp(project.costOverrunRisk+8);}if(i.status==='FAILED')news.push(`A property inspection failed, creating remediation work and schedule pressure.`);}}
 for(const c of r.constructionContracts){if(c.status!=='ACTIVE')continue;const builder=r.contractors.find(x=>x.id===c.contractorId);c.progress=Math.min(100,c.progress+(builder?.quality||70)/100*5);if(random()<.04){c.value*=1.03;c.variationReserve=Math.max(0,c.variationReserve-c.value*.02);news.push(`A construction contract recorded a variation order after changing site conditions.`);}if(c.progress>=100)c.status='COMPLETED';}
 for(const f of r.developmentFinancing){if(f.status==='COMMITTED'&&random()<.2){f.drawn=Math.min(f.amount,f.drawn+f.amount*.12);}}
 for(const a of r.auctions){if(a.status!=='OPEN')continue;a.monthsOpen++;if(random()<.35){a.bidderCount++;a.currentBid=Math.max(a.currentBid,a.reservePrice*(1+.05*a.bidderCount)*(0.95+random()*.15));}if(a.monthsOpen>=2&&a.currentBid>=a.reservePrice){a.status='SOLD';news.push(`A property auction closed successfully at $${Math.round(a.currentBid).toLocaleString()}.`);}}
 for(const d of r.distressedAssets){if(d.status==='WATCH'&&random()<.1)d.status='LISTED';}
 for(const reit of r.reits){reit.aum=Math.max(0,reit.aum*(1+pressure+(random()-.5)*.01));reit.occupancy=clamp(reit.occupancy+(92-vacancy-reit.occupancy)*.05);reit.leverage=clamp(reit.leverage+(pressure<-.02?1:-.1));reit.dividendYield=Math.max(1,Math.min(12,reit.dividendYield+(random()-.5)*.08));}
 // Property-company employees are persistent NPC-linked organizational records.
 for(const c of state.companies){if(!['Real Estate','Construction','Property Management','Hospitality'].some(k=>c.industry.toLowerCase().includes(k.toLowerCase())))continue;const existing=r.companyEmployees.filter(e=>e.companyId===c.id);if(existing.length===0){const n=Math.min(12,Math.max(3,Math.round((c.employeesCount||10)/20)));for(let i=0;i<n;i++)r.companyEmployees.push({id:`reemp_${c.id}_${i}`,companyId:c.id,npcId:state.livingWorld?.npcs[i]?.id,name:state.livingWorld?.npcs[i]?.name||`Property Employee ${i+1}`,role:['Development Manager','Property Manager','Leasing Manager','Project Engineer','Estimator','Facilities Manager'][i%6],salaryMonthly:Math.max(2500,(c.averageEmployeeSalary||3000)*(0.8+i*.08)),performance:65+Math.round(random()*25),morale:c.employeeMorale||70,status:'ACTIVE' as const});}}
 if(state.simulationTick%6===0)pushHistory(state,'Real estate market pulse',`Agents, tenants, lenders, contractors and institutional investors respond to ${macro?.currentCycle||'stable'} economic conditions.`);
 r.lastProcessedTick=state.simulationTick;
}
