import React from 'react';
import {
  // Navigation & Core
  LayoutGrid,
  LayoutList,
  User,
  Users,
  DollarSign,
  Building2,
  Building,
  Globe,
  Menu,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Play,
  Pause,
  Loader2,
  Settings,
  ShieldCheck,
  ShieldAlert,
  Shield,
  Activity,
  Sparkles,
  Zap,
  HelpCircle,
  Info,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Filter,
  ArrowUpDown,
  RefreshCw,
  Maximize2,
  Minimize2,
  Plus,
  Minus,
  Trash2,
  Edit3,
  Copy,
  Share2,
  Download,
  Upload,
  Calendar,
  Clock,
  History,
  Target,
  Inbox,
  GitBranch,

  // Career, Work & Education
  Briefcase,
  GraduationCap,
  Award,
  Crown,
  BookOpen,
  FileText,
  FileCheck,
  FileSpreadsheet,
  Award as Certificate,
  Stethoscope,
  Scale,
  Gavel,
  Cpu,
  Code,
  Laptop,
  Terminal,
  Wrench,
  Hammer,
  HardHat,
  Compass,
  Lightbulb,
  Brain,
  MessageSquare,
  Handshake,
  TrendingUp,
  TrendingDown,

  // Finance, Wealth & Banking
  Wallet,
  Coins,
  CreditCard,
  Landmark,
  PiggyBank,
  Receipt,
  Banknote,
  Percent,
  Calculator,
  Flame,
  ArrowDownLeft,
  ArrowUpRight,
  RefreshCcw,
  CircleDollarSign,

  // Investments & Markets
  LineChart,
  BarChart3,
  CandlestickChart,
  PieChart,
  Boxes,
  Gem,
  Fuel,
  Sun,
  Wind,
  Atom,
  Vote,
  Factory,
  Store,
  Hotel,
  Home,
  Warehouse,
  MapPin,

  // Legal, Politics & World
  Flag,
  Radio,
  Tv,
  Newspaper,
  Megaphone,
  Mic,
  Camera,
  Heart,
  HeartPulse,
  ShoppingBag,
  Smile,
  Frown,
  Meh,
  Trophy,
  Plane,
  Ship,
  Truck,
  ShieldCheck as ShieldVerified,
  Key,
  FolderOpen
} from 'lucide-react';

export type IconSizeToken = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export type IconVariant = 
  | 'default' 
  | 'muted' 
  | 'active' 
  | 'success' 
  | 'warning' 
  | 'danger' 
  | 'info' 
  | 'accent' 
  | 'gold'
  | 'purple'
  | 'cyan'
  | 'disabled';

export type DomainCategory = 
  | 'navigation'
  | 'career'
  | 'education'
  | 'skills'
  | 'finance'
  | 'banking'
  | 'credit'
  | 'investments'
  | 'markets'
  | 'charts'
  | 'property'
  | 'construction'
  | 'business'
  | 'corporate'
  | 'legal'
  | 'politics'
  | 'government'
  | 'resources'
  | 'world'
  | 'security'
  | 'family'
  | 'relationships'
  | 'npc'
  | 'power'
  | 'events'
  | 'media'
  | 'stories'
  | 'status'
  | 'risk'
  | 'actions'
  | 'system';

/**
 * MASTER SEMANTIC ICON REGISTRY FOR DOMINIUM
 * Maps structured semantic identifiers to Lucide React component definitions.
 */
export const DOMINIUM_ICON_REGISTRY: Record<string, React.ComponentType<{ className?: string; size?: number | string; style?: React.CSSProperties }>> = {
  // 1. NAVIGATION DOMAIN
  'nav.home': LayoutGrid,
  'nav.chronology': LayoutList,
  'nav.inbox': Inbox,
  'nav.objectives': Target,
  'nav.history': History,
  'nav.event_chains': GitBranch,
  'nav.event_monitor': Activity,
  'nav.life': User,
  'nav.family': Users,
  'nav.wealth': DollarSign,
  'nav.empire': Building2,
  'nav.politics': Landmark,
  'nav.government': Building,
  'nav.economy': TrendingUp,
  'nav.projects': BookOpen,
  'nav.sports': Trophy,
  'nav.news': Newspaper,
  'nav.world': Globe,
  'nav.settings': Settings,
  'nav.more': Menu,
  'nav.tests': ShieldCheck,
  'nav.power': Zap,

  // 2. CAREER & OCCUPATION DOMAIN
  'career.general': Briefcase,
  'career.business': Building2,
  'career.finance': DollarSign,
  'career.law': Scale,
  'career.tech': Cpu,
  'career.medicine': Stethoscope,
  'career.engineering': Compass,
  'career.education': GraduationCap,
  'career.government': Landmark,
  'career.media': Megaphone,
  'career.science': Atom,
  'career.trades': Hammer,
  'career.entrepreneurship': Sparkles,
  'career.promotion': ArrowUpRight,
  'career.bonus': Award,
  'career.interview': Handshake,
  'career.license': Award,
  'career.workload': Clock,

  // Specific Occupations
  'occupation.ceo': Crown,
  'occupation.executive': Briefcase,
  'occupation.manager': Users,
  'occupation.lawyer': Scale,
  'occupation.judge': Gavel,
  'occupation.doctor': Stethoscope,
  'occupation.nurse': HeartPulse,
  'occupation.banker': Landmark,
  'occupation.analyst': LineChart,
  'occupation.developer': Code,
  'occupation.engineer': Compass,
  'occupation.architect': Building,
  'occupation.professor': BookOpen,
  'occupation.teacher': GraduationCap,
  'occupation.scientist': Atom,
  'occupation.journalist': Newspaper,
  'occupation.politician': Vote,
  'occupation.diplomat': Globe,
  'occupation.trader': BarChart3,
  'occupation.accountant': Calculator,
  'occupation.consultant': Lightbulb,
  'occupation.contractor': HardHat,

  // 3. SKILLS & EDUCATION DOMAIN
  'skill.general': Brain,
  'skill.intelligence': Brain,
  'skill.charisma': Sparkles,
  'skill.discipline': ShieldCheck,
  'skill.creativity': Lightbulb,
  'skill.knowledge': BookOpen,
  'skill.leadership': Crown,
  'skill.negotiation': Handshake,
  'skill.communication': MessageSquare,
  'skill.management': Users,
  'skill.finance': DollarSign,
  'skill.technology': Cpu,
  'skill.law': Scale,
  'skill.research': Search,
  'skill.sales': TrendingUp,
  'skill.strategy': Target,

  // Education
  'edu.degree': GraduationCap,
  'edu.diploma': FileText,
  'edu.license': Award,
  'edu.certificate': FileCheck,
  'edu.university': Landmark,
  'edu.school': BookOpen,
  'edu.exam': FileSpreadsheet,
  'edu.study': Clock,
  'edu.graduation': Award,

  // 4. FINANCE, WEALTH & BANKING DOMAIN
  'finance.wealth': DollarSign,
  'finance.networth': Trophy,
  'finance.cash': Banknote,
  'finance.coins': Coins,
  'finance.wallet': Wallet,
  'finance.income': ArrowDownLeft,
  'finance.salary': CircleDollarSign,
  'finance.bonus': Sparkles,
  'finance.profit': TrendingUp,
  'finance.dividend': Coins,
  'finance.expense': ArrowUpRight,
  'finance.bill': Receipt,
  'finance.tax': Landmark,
  'finance.distress': Flame,
  'finance.recovery': RefreshCw,
  'finance.asset': Boxes,
  'finance.liability': Receipt,

  // Banking
  'banking.bank': Landmark,
  'banking.vault': Lock,
  'banking.account': CreditCard,
  'banking.checking': Wallet,
  'banking.savings': PiggyBank,
  'banking.highyield': TrendingUp,
  'banking.cd': Lock,
  'banking.moneymarket': LineChart,
  'banking.offshore': Globe,
  'banking.deposit': ArrowDownLeft,
  'banking.withdraw': ArrowUpRight,
  'banking.transfer': RefreshCcw,
  'banking.interest': Percent,
  'banking.fee': Receipt,
  'banking.statement': FileSpreadsheet,

  // 5. CREDIT, LOANS & DEBT DOMAIN
  'credit.score': Award,
  'credit.report': FileText,
  'credit.card': CreditCard,
  'credit.loan': Handshake,
  'credit.mortgage': Home,
  'credit.auto': Truck,
  'credit.business': Building2,
  'credit.line': RefreshCcw,
  'credit.debt': Receipt,
  'credit.payment': CheckCircle2,
  'credit.arrears': AlertTriangle,
  'credit.default': AlertCircle,
  'credit.collection': ShieldAlert,
  'credit.collateral': Lock,
  'credit.restructure': RefreshCw,

  // 6. INVESTMENTS, ASSETS & MARKETS DOMAIN
  'investment.portfolio': PieChart,
  'investment.stock': LineChart,
  'investment.shares': BarChart3,
  'investment.exchange': Building2,
  'investment.etf': Boxes,
  'investment.bond': FileCheck,
  'investment.govtbond': Landmark,
  'investment.commodity': Gem,
  'investment.gold': Gem,
  'investment.silver': Gem,
  'investment.oil': Fuel,
  'investment.energy': Sun,
  'investment.crypto': Cpu,
  'investment.startup': Sparkles,
  'investment.pe': Handshake,
  'investment.vc': TrendingUp,

  // Market Trends & Charts
  'market.bull': TrendingUp,
  'market.bear': TrendingDown,
  'market.volatility': Activity,
  'market.crash': Flame,
  'market.growth': ArrowUpRight,
  'market.analytics': BarChart3,
  'market.forecast': LineChart,
  'chart.line': LineChart,
  'chart.bar': BarChart3,
  'chart.candlestick': CandlestickChart,
  'chart.pie': PieChart,
  'trend.up': TrendingUp,
  'trend.down': TrendingDown,
  'trend.stable': Activity,
  'trend.volatile': Flame,

  // 7. PROPERTY, REAL ESTATE & CONSTRUCTION
  'property.general': Building,
  'property.house': Home,
  'property.apartment': Building,
  'property.townhouse': Home,
  'property.villa': CastleIconFallback(Building2),
  'property.mansion': CastleIconFallback(Building2),
  'property.estate': Building2,
  'property.penthouse': Building2,
  'property.office': Building,
  'property.retail': Store,
  'property.plaza': Store,
  'property.hotel': Hotel,
  'property.warehouse': Warehouse,
  'property.industrial': Factory,
  'property.land': MapPin,
  'property.farmland': Compass,
  'property.renovate': Hammer,
  'property.repair': Wrench,
  'property.tenant': User,
  'property.inspection': FileCheck,

  // Construction & Development
  'construction.blueprint': FileText,
  'construction.site': HardHat,
  'construction.crane': Compass,
  'construction.tools': Hammer,
  'construction.materials': Boxes,
  'construction.permit': FileCheck,
  'construction.timeline': Clock,
  'construction.complete': CheckCircle2,
  'construction.delay': AlertTriangle,

  // 8. BUSINESS, CORPORATE & M&A
  'business.company': Building2,
  'business.corporation': Building2,
  'business.startup': Sparkles,
  'business.smallbiz': Store,
  'business.holding': Building,
  'business.hq': Building2,
  'business.boardroom': Users,
  'business.revenue': DollarSign,
  'business.profit': TrendingUp,
  'business.loss': TrendingDown,
  'business.growth': ArrowUpRight,
  'business.competition': Trophy,
  'business.crisis': Flame,

  // Departments
  'dept.finance': DollarSign,
  'dept.operations': Wrench,
  'dept.hr': Users,
  'dept.marketing': Megaphone,
  'dept.sales': TrendingUp,
  'dept.rd': Lightbulb,
  'dept.production': Factory,
  'dept.supply': Truck,

  // Mergers & Acquisitions
  'ma.target': Target,
  'ma.acquisition': Handshake,
  'ma.merger': GitBranch,
  'ma.takeover': Crown,
  'ma.valuation': Calculator,
  'ma.duediligence': Search,
  'ma.offer': FileText,
  'ma.synergy': Sparkles,
  'ma.integration': RefreshCw,

  // 9. LEGAL, JUSTICE & COURTS
  'legal.law': Scale,
  'legal.justice': Scale,
  'legal.court': Landmark,
  'legal.judge': Gavel,
  'legal.lawyer': Briefcase,
  'legal.counsel': Scale,
  'legal.evidence': Search,
  'legal.casefile': FolderOpen,
  'legal.contract': FileText,
  'legal.signature': FileCheck,
  'legal.judgment': Gavel,
  'legal.settlement': Handshake,
  'legal.appeal': RefreshCw,
  'legal.dispute': AlertTriangle,
  'legal.penalty': Receipt,
  'legal.fine': DollarSign,
  'legal.bankruptcy': Flame,
  'legal.injunction': ShieldAlert,

  // 10. POLITICS & ELECTIONS
  'politics.politics': Landmark,
  'politics.party': Users,
  'politics.faction': GitBranch,
  'politics.campaign': Megaphone,
  'politics.election': Vote,
  'politics.vote': Vote,
  'politics.ballot': FileCheck,
  'politics.candidate': User,
  'politics.debate': MessageSquare,
  'politics.speech': Mic,
  'politics.manifesto': BookOpen,
  'politics.fundraising': Coins,
  'politics.endorsement': Award,
  'politics.poll': BarChart3,
  'politics.scandal': AlertCircle,
  'politics.protest': Megaphone,

  // Political Offices
  'office.mayor': Landmark,
  'office.governor': Building,
  'office.legislator': Vote,
  'office.parliament': Building2,
  'office.minister': Crown,
  'office.cabinet': Users,
  'office.president': Crown,
  'office.primeminister': Crown,

  // 11. GOVERNMENT & PUBLIC POLICY
  'govt.government': Landmark,
  'govt.building': Building,
  'govt.treasury': Landmark,
  'govt.budget': Calculator,
  'govt.taxation': Receipt,
  'govt.spending': ArrowUpRight,
  'govt.nationaldebt': AlertTriangle,
  'govt.economy': Globe,
  'govt.infrastructure': Compass,
  'govt.healthcare': HeartPulse,
  'govt.education': GraduationCap,
  'govt.energy': Sun,
  'govt.policy': FileText,
  'govt.report': FileSpreadsheet,

  // 12. NATIONAL STRATEGIC RESOURCES & ASSETS
  'resource.gold': Gem,
  'resource.diamonds': Gem,
  'resource.minerals': Boxes,
  'resource.coal': Fuel,
  'resource.oil': Fuel,
  'resource.gas': Fuel,
  'resource.water': Compass,
  'resource.forest': Compass,
  'resource.agriculture': Compass,
  'resource.energy': Sun,
  'resource.solar': Sun,
  'resource.wind': Wind,
  'resource.nuclear': Atom,
  'asset.mine': HardHat,
  'asset.oilfield': Fuel,
  'asset.refinery': Factory,
  'asset.powerplant': Sun,
  'asset.port': Ship,
  'asset.airport': Plane,
  'asset.railway': Compass,
  'asset.telecom': Radio,
  'asset.dam': Compass,

  // 13. WORLD, GEOPOLITICS & DEFENSE
  'world.globe': Globe,
  'world.country': Flag,
  'world.city': Building,
  'world.map': Compass,
  'world.flag': Flag,
  'world.population': Users,
  'world.trade': RefreshCw,
  'world.diplomacy': Handshake,
  'world.alliance': ShieldCheck,
  'world.treaty': FileCheck,
  'world.sanctions': ShieldAlert,
  'world.embassy': Landmark,
  'defense.defense': Shield,
  'defense.security': ShieldCheck,
  'defense.readiness': Activity,
  'defense.border': Shield,
  'defense.peace': Heart,
  'defense.alert': AlertTriangle,

  // 14. FAMILY, DYNASTY & SUCCESSION
  'family.family': Users,
  'family.parent': Users,
  'family.child': User,
  'family.spouse': Heart,
  'family.marriage': Heart,
  'family.divorce': XCircle,
  'family.birth': Sparkles,
  'family.death': Clock,
  'family.inheritance': Coins,
  'family.estate': Building2,
  'family.will': FileCheck,
  'family.legacy': Crown,
  'family.dynasty': Crown,
  'family.tree': GitBranch,
  'family.generation': Clock,
  'family.heir': Award,
  'family.succession': Trophy,

  // Relationships
  'rel.love': Heart,
  'rel.friendship': Smile,
  'rel.trust': ShieldCheck,
  'rel.loyalty': Award,
  'rel.respect': Trophy,
  'rel.conflict': AlertTriangle,
  'rel.rivalry': Trophy,
  'rel.betrayal': AlertCircle,
  'rel.reconciliation': Handshake,

  // 15. NPC, PERSONALITY & POWER
  'npc.person': User,
  'npc.avatar': User,
  'trait.ambition': Trophy,
  'trait.confidence': Crown,
  'trait.charisma': Sparkles,
  'trait.intelligence': Brain,
  'trait.discipline': ShieldCheck,
  'trait.creativity': Lightbulb,
  'trait.greed': DollarSign,
  'trait.generosity': Heart,
  'trait.patience': Clock,
  'trait.integrity': ShieldVerified,
  'mood.happy': Smile,
  'mood.angry': AlertCircle,
  'mood.sad': Frown,
  'mood.stressed': Flame,
  'mood.neutral': Meh,

  // Power Hierarchy
  'power.reputation': Award,
  'power.prestige': Crown,
  'power.fame': Sparkles,
  'power.influence': Globe,
  'power.authority': Landmark,
  'power.tier.local': User,
  'power.tier.regional': Building,
  'power.tier.national': Flag,
  'power.tier.continental': Globe,
  'power.tier.global': Crown,
  'power.tier.legendary': Sparkles,

  // 16. EVENTS, MEDIA & STORIES
  'event.opportunity': Sparkles,
  'event.decision': Inbox,
  'event.crisis': Flame,
  'event.emergency': AlertCircle,
  'event.achievement': Trophy,
  'event.milestone': Award,
  'event.surprise': Lightbulb,
  'event.chain': GitBranch,
  'media.news': Newspaper,
  'media.breaking': Radio,
  'media.newspaper': Newspaper,
  'media.tv': Tv,
  'media.camera': Camera,
  'media.social': Share2,
  'media.viral': Flame,
  'story.timeline': Clock,
  'story.chronicle': BookOpen,
  'story.memory': History,
  'story.secret': Key,
  'story.scandal': AlertCircle,

  // 17. RISK, STATUS & SEVERITY
  'risk.safe': ShieldCheck,
  'risk.low': ShieldCheck,
  'risk.moderate': AlertTriangle,
  'risk.high': AlertTriangle,
  'risk.critical': AlertCircle,
  'risk.emergency': Flame,

  'status.locked': Lock,
  'status.unlocked': Unlock,
  'status.active': CheckCircle2,
  'status.inactive': Minus,
  'status.pending': Clock,
  'status.approved': CheckCircle2,
  'status.rejected': XCircle,
  'status.completed': CheckCircle2,
  'status.inprogress': Loader2,
  'status.paused': Pause,
  'status.failed': XCircle,
  'status.cancelled': XCircle,
  'status.expired': Clock,
  'status.profitable': TrendingUp,
  'status.loss': TrendingDown,
  'status.growing': ArrowUpRight,
  'status.declining': ArrowDownLeft,

  // 18. CORE GAMEPLAY ACTIONS
  'action.add': Plus,
  'action.remove': Minus,
  'action.edit': Edit3,
  'action.view': Eye,
  'action.search': Search,
  'action.filter': Filter,
  'action.sort': ArrowUpDown,
  'action.refresh': RefreshCw,
  'action.expand': Maximize2,
  'action.collapse': Minimize2,
  'action.confirm': CheckCircle2,
  'action.cancel': XCircle,
  'action.save': Download,
  'action.load': Upload,
  'action.delete': Trash2,
  'action.copy': Copy,
  'action.share': Share2,
  'action.transfer': RefreshCcw,
  'action.buy': ShoppingBag,
  'action.sell': DollarSign,
  'action.invest': TrendingUp,
  'action.withdraw': ArrowUpRight,
  'action.deposit': ArrowDownLeft,
  'action.borrow': CreditCard,
  'action.repay': CheckCircle2,
  'action.apply': FileText,
  'action.accept': CheckCircle2,
  'action.reject': XCircle,
  'action.negotiate': Handshake,
  'action.approve': CheckCircle2,
  'action.decline': XCircle,
  'action.hire': User,
  'action.fire': XCircle,
  'action.promote': Crown,
  'action.manage': Settings,
  'action.upgrade': ArrowUpRight,
  'action.build': Hammer,
  'action.repair': Wrench,
  'action.merge': GitBranch,
  'action.acquire': Handshake,
  'action.sue': Scale,
  'action.settle': Handshake,
  'action.appeal': RefreshCw,
  'action.vote': Vote,
  'action.campaign': Megaphone,
  'action.appoint': Award,
  'action.advance': Play,
  'action.settings': Settings,
  'action.help': HelpCircle,

  // 19. SYSTEM & GENERAL FALLBACKS
  'system.fallback': Sparkles,
  'system.object': Boxes,
  'system.document': FileText,
  'system.unknown': HelpCircle,
  'system.info': Info,
  'system.diagnostics': ShieldCheck,
  'system.loading': Loader2
};

function CastleIconFallback(FallbackComponent: React.ComponentType<any>) {
  return FallbackComponent;
}

export type SemanticIconKey = keyof typeof DOMINIUM_ICON_REGISTRY | string;
