import React,{useState} from 'react';
import {GameState,GovernmentMinistry} from '../../types';
import {ensureGovernmentLivingProfile,appointCivilServant,passGovernmentBill,allocateGovernmentBudget,launchPublicProject,awardProcurement,setTaxRate,conductDiplomacy} from '../../engine/governmentLivingEngine';
import {ensureGovernmentMachinery,callCabinetMeeting,proposeMinistryPolicy,issueGovernmentDebt,openProcurementTender,submitCorporateLobbying,openGovernmentInvestigation,fileConstitutionalCase} from '../../engine/governmentMachineryEngine';
import {Building2,Users,Landmark,Vote,Receipt,Globe2,AlertTriangle,BriefcaseBusiness} from 'lucide-react';

export const LivingGovernmentCommandCenter:React.FC<{state:GameState;onStateChange?:(s:GameState)=>void}> = ({state,onStateChange})=>{
 const [tab,setTab]=useState<'cabinet'|'machinery'|'parliament'|'budget'|'projects'|'diplomacy'|'social'>('cabinet');
 const [ministry,setMinistry]=useState<GovernmentMinistry>('Finance');
 const [amount,setAmount]=useState(10000000); const [bill,setBill]=useState('National Public Investment Act'); const [tax,setTax]=useState(28); const [project,setProject]=useState('National Infrastructure Renewal');
 const g=state.governmentLiving||ensureGovernmentLivingProfile(state); const country=state.world[state.currentCountryIndex];
 const act=(fn:(s:GameState)=>any)=>{const next=structuredClone(state);const r=fn(next);if(r?.success!==false){onStateChange?.(next);} return r;};
 const canNational=state.politics.currentOffice.inOffice && (state.politics.currentOffice.title.includes('President')||state.politics.currentOffice.title.includes('Prime')||state.politics.currentOffice.title.includes('Minister'));
 return <div className="space-y-4">
  <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5">
   <div className="flex items-center justify-between"><div><span className="text-[10px] uppercase tracking-widest text-amber-400 font-black">Living Government</span><h2 className="text-xl font-black text-zinc-100">State Administration Command Center</h2><p className="text-xs text-zinc-400 mt-1">NPC ministries, parliament, public finance, projects, procurement, social pressure and diplomacy operate continuously in the living world.</p></div><Landmark className="w-8 h-8 text-amber-400"/></div>
   <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-4 text-xs"><Metric label="Treasury" value={`$${(g.budget.totalRevenue-g.budget.deficit).toLocaleString()}`}/><Metric label="Deficit" value={`$${Math.round(g.budget.deficit).toLocaleString()}`}/><Metric label="Approval" value={`${country?.publicApprovalOfGov||0}%`}/><Metric label="Parliament" value={`${g.parliamentarians.length} NPCs`}/><Metric label="Projects" value={`${g.projects.filter(p=>p.status==='ACTIVE').length} active`}/></div>
  </div>
  <div className="flex gap-1 overflow-x-auto">{[['cabinet','Ministries'],['machinery','Machinery'],['parliament','Parliament'],['budget','Budget & Tax'],['projects','Projects & Procurement'],['diplomacy','Diplomacy'],['social','Public Pressure']].map(([k,l])=><button key={k} onClick={()=>setTab(k as any)} className={`px-3 py-2 rounded-xl text-xs font-black whitespace-nowrap ${tab===k?'bg-amber-400 text-zinc-950':'bg-zinc-900 text-zinc-400 border border-zinc-800'}`}>{l}</button>)}</div>
  {tab==='cabinet'&&<Section icon={<Users/>} title="NPC Ministries & Civil Service"><div className="grid md:grid-cols-2 gap-2">{g.ministries.map(m=><div key={m.id} className="bg-zinc-950 border border-zinc-800 rounded-xl p-3"><div className="flex justify-between"><b>{m.name}</b><span className="text-amber-400">Capacity {m.capacity.toFixed(0)}</span></div><div className="text-[11px] text-zinc-500">Budget ${Math.round(m.budget).toLocaleString()} · {m.headcount.toLocaleString()} civil servants</div><button onClick={()=>{setMinistry(m.name); const n=g.civilServants.find(c=>c.ministry===m.name); const r=act(s=>appointCivilServant(s,m.name)); alert(r.message)}} className="mt-2 px-3 py-1.5 bg-zinc-800 rounded-lg text-xs">Appoint NPC senior official</button></div>)}</div></Section>}
  {tab==='machinery'&&<Section icon={<BriefcaseBusiness/>} title="Machinery of Government"><div className="grid md:grid-cols-2 gap-3"><div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 space-y-2"><b>Cabinet & Policy</b><button disabled={!canNational} onClick={()=>{const r=act(s=>callCabinetMeeting(s,['Economic outlook','Public services','National security']));alert(r.message)}} className="block w-full px-3 py-2 bg-amber-400 text-zinc-950 rounded-xl text-xs font-black">Convene Cabinet</button><button disabled={!canNational} onClick={()=>{const r=act(s=>proposeMinistryPolicy(s,ministry,{title:`${ministry} Modernisation Programme`,cost:10000000,expectedGrowth:1.2,expectedApproval:3,risk:25,rationale:'Improve institutional capacity and service delivery.'}));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Submit Ministry Policy</button><button disabled={!canNational} onClick={()=>{const r=act(s=>issueGovernmentDebt(s,'GOVERNMENT_BOND',25000000,60,5.2));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Issue Government Bond</button></div><div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 space-y-2"><b>Oversight, Procurement & Courts</b><button disabled={!canNational} onClick={()=>{const r=act(s=>openProcurementTender(s,'National Infrastructure Tender','Infrastructure',15000000));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Run Competitive Tender</button><button onClick={()=>{const r=act(s=>submitCorporateLobbying(s,'Corporate Industry Coalition','Tax Policy',35));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Register Lobbying</button><button onClick={()=>{const r=act(s=>openGovernmentInvestigation(s,'Procurement Integrity Review','CORRUPTION',[],s.companies.slice(0,2).map(c=>c.id)));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Open Integrity Investigation</button><button onClick={()=>{const r=act(s=>fileConstitutionalCase(s,'Executive Powers Challenge','Public Interest Group',s.character.firstName+' '+s.character.lastName,'Scope of executive authority'));alert(r.message)}} className="block w-full px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">File Constitutional Case</button></div></div><div className="grid md:grid-cols-3 gap-2 mt-3"><Metric label="Committees" value={`${ensureGovernmentMachinery(state).committees.length}`}/><Metric label="Investigations" value={`${ensureGovernmentMachinery(state).investigations.length}`}/><Metric label="Tenders" value={`${ensureGovernmentMachinery(state).tenders.length}`}/></div></Section>}
  {tab==='parliament'&&<Section icon={<Vote/>} title="Parliamentary Government"><div className="grid md:grid-cols-2 gap-3"><div><label className="text-xs text-zinc-400">Bill</label><input value={bill} onChange={e=>setBill(e.target.value)} className="w-full mt-1 bg-zinc-950 border border-zinc-800 rounded-xl px-3 py-2 text-sm"/><button disabled={!canNational} onClick={()=>{const r=act(s=>passGovernmentBill(s,bill,'PUBLIC_SERVICES',25000000));alert(r.message)}} className="mt-2 px-4 py-2 rounded-xl bg-amber-400 text-zinc-950 text-xs font-black disabled:opacity-40">Introduce & Vote</button></div><div className="space-y-2">{g.bills.slice(0,5).map(b=><div key={b.id} className="bg-zinc-950 p-3 rounded-xl border border-zinc-800 text-xs"><b>{b.title}</b><div className="text-zinc-500 mt-1">{b.status} · Support {b.supportFor.toFixed(0)}% · Cost ${b.fiscalCost.toLocaleString()}</div></div>)}</div></div></Section>}
  {tab==='budget'&&<Section icon={<Receipt/>} title="Public Finance & Monetary Policy"><div className="grid md:grid-cols-2 gap-3"><div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800"><b>Tax Policy</b><input type="number" value={tax} onChange={e=>setTax(Number(e.target.value))} className="w-full mt-2 bg-zinc-900 rounded-lg p-2"/><button disabled={!canNational} onClick={()=>{const r=act(s=>setTaxRate(s,tax));alert(r.message)}} className="mt-2 px-3 py-2 bg-amber-400 text-zinc-950 rounded-xl text-xs font-black">Set national income tax</button></div><div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800"><b>Department Allocation</b><select value={ministry} onChange={e=>setMinistry(e.target.value as GovernmentMinistry)} className="w-full mt-2 bg-zinc-900 rounded-lg p-2">{g.ministries.map(m=><option key={m.id}>{m.name}</option>)}</select><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))} className="w-full mt-2 bg-zinc-900 rounded-lg p-2"/><button disabled={!canNational} onClick={()=>{const r=act(s=>allocateGovernmentBudget(s,ministry,amount));alert(r.message)}} className="mt-2 px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Allocate budget</button></div></div></Section>}
  {tab==='projects'&&<Section icon={<Building2/>} title="Public Projects & Procurement"><div className="grid md:grid-cols-2 gap-3"><div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800"><input value={project} onChange={e=>setProject(e.target.value)} className="w-full bg-zinc-900 rounded-lg p-2"/><button disabled={!canNational} onClick={()=>{const r=act(s=>launchPublicProject(s,project,'INFRASTRUCTURE',50000000));alert(r.message)}} className="mt-2 px-3 py-2 bg-amber-400 text-zinc-950 rounded-xl text-xs font-black">Launch project</button><button disabled={!canNational} onClick={()=>{const r=act(s=>awardProcurement(s,`${project} Procurement`,'Infrastructure',s.companies[0]?.name||'State Supplier',10000000));alert(r.message)}} className="ml-2 mt-2 px-3 py-2 bg-zinc-800 rounded-xl text-xs font-black">Award procurement</button></div><div className="space-y-2">{g.projects.slice(-5).reverse().map(p=><div key={p.id} className="bg-zinc-950 p-3 rounded-xl border border-zinc-800 text-xs"><b>{p.name}</b><div className="text-zinc-500">{p.status} · {p.progress.toFixed(0)}% · {p.jobsCreated} jobs</div></div>)}</div></div></Section>}
  {tab==='diplomacy'&&<Section icon={<Globe2/>} title="International Diplomacy"><div className="grid md:grid-cols-2 gap-2">{g.diplomacy.map(d=><div key={d.countryId} className="bg-zinc-950 p-3 rounded-xl border border-zinc-800"><b>{d.countryName}</b><div className="text-xs text-zinc-500">Relations {d.relationship} · Trade {d.tradeAlignment} · Trust {d.trust}</div><div className="mt-2 flex gap-1">{(['SUMMIT','TRADE_DEAL','TREATY','SANCTIONS'] as const).map(a=><button key={a} disabled={!canNational} onClick={()=>{const r=act(s=>conductDiplomacy(s,d.countryId,a));alert(r.message)}} className="px-2 py-1 bg-zinc-800 rounded text-[10px]">{a.replace('_',' ')}</button>)}</div></div>)}</div></Section>}
  {tab==='social'&&<Section icon={<AlertTriangle/>} title="Social Pressure & Government Integrity"><div className="grid md:grid-cols-2 gap-2">{g.demographics.map(d=><div key={d.group} className="bg-zinc-950 p-3 rounded-xl border border-zinc-800 text-xs"><div className="flex justify-between"><b>{d.group}</b><span className={d.approval<40?'text-red-400':'text-emerald-400'}>{d.approval.toFixed(0)}%</span></div><div className="h-1 bg-zinc-800 rounded mt-2"><div className="h-1 bg-amber-400 rounded" style={{width:`${d.approval}%`}}/></div></div>)}</div><div className="mt-3 space-y-2">{g.scandals.slice(0,5).map(x=><div key={x.id} className="p-3 bg-red-500/5 border border-red-500/20 rounded-xl text-xs"><b>{x.title}</b><div className="text-zinc-500">{x.severity} · {x.resolved?'Resolved':'Active inquiry'}</div></div>)}</div></Section>}
 </div>
}
const Metric=({label,value}:{label:string,value:string})=><div className="bg-zinc-950/70 border border-zinc-800 rounded-xl p-3"><div className="text-[9px] text-zinc-500 uppercase font-black">{label}</div><div className="text-sm font-black text-zinc-200 mt-1">{value}</div></div>;
const Section=({icon,title,children}:{icon:React.ReactNode,title:string,children:React.ReactNode})=><div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5"><div className="flex items-center gap-2 mb-4 text-amber-400"><span className="w-5 h-5">{icon}</span><h3 className="text-lg font-black text-zinc-100">{title}</h3></div>{children}</div>;
